import { EnemyConfig } from '../types/index'

export const ENEMY_CONFIGS: EnemyConfig[] = [
  {
    id: 'soldier',
    name: 'Scout Car',
    description: 'Light scout. Low DEF — focus ranged fire to clear quickly.',
    hp: 2200,
    atk: 280,
    armor: 100,
    res: 0,
    speed: 60,
    color: 0xe74c3c,
    dpOnKill: 1,
    attackInterval: 2.0,
    damageType: 'kinetic',
  },
  {
    id: 'trooper',
    name: 'APC',
    description: 'Armored transport. Moderate DEF and RES. Use casters or sustained fire.',
    hp: 3000,
    atk: 350,
    armor: 150,
    res: 5,
    speed: 42,
    color: 0xc0392b,
    dpOnKill: 2,
    attackInterval: 2.5,
    damageType: 'kinetic',
  },
  {
    id: 'heavy',
    name: 'Tank',
    description: 'Heavy assault vehicle. Very high DEF — thermal damage bypasses armor.',
    hp: 8000,
    atk: 600,
    armor: 400,
    res: 10,
    speed: 30,
    color: 0x8e44ad,
    dpOnKill: 3,
    attackInterval: 2.5,
    damageType: 'kinetic',
  },
  {
    id: 'drone',
    name: 'Drone',
    description: 'Aerial recon — flies over ground blockers. Requires ranged units.',
    hp: 1500,
    atk: 200,
    armor: 50,
    res: 0,
    speed: 72,
    color: 0xf39c12,
    dpOnKill: 1,
    attackInterval: 1.5,
    damageType: 'kinetic',
    isAerial: true,
    attackRange: 2.5,
  },
  {
    id: 'caster',
    name: 'Artillery Caster',
    description: 'Indirect fire — thermal damage bypasses DEF. Prioritize elimination.',
    hp: 2500,
    atk: 250,
    armor: 80,
    res: 0,
    speed: 36,
    color: 0x9b59b6,
    dpOnKill: 2,
    attackInterval: 3.5,
    damageType: 'thermal',
    attackRange: 2.5,
  },
]
