import { EnemyConfig } from '../types/index'

export const ENEMY_CONFIGS: EnemyConfig[] = [
  {
    id: 'soldier', name: 'Scout Car',
    description: 'Light scout. Low DEF — focus ranged fire to clear quickly.',
    weight: 0, hp: 2200, atk: 280, armor: 100, res: 0, speed: 60,
    color: 0xe74c3c, dpOnKill: 1, attackInterval: 2.0, damageType: 'kinetic',
    behavior: { type: 'standard' },
  },
  {
    id: 'soldier_elite', name: 'Scout Car Elite',
    description: 'Hardened scout vehicle.',
    weight: 1, hp: 3300, atk: 360, armor: 130, res: 0, speed: 60,
    color: 0x808080, dpOnKill: 2, attackInterval: 2.0, damageType: 'kinetic',
    behavior: { type: 'standard' },
  },
  {
    id: 'trooper', name: 'APC',
    description: 'Armored transport. Moderate DEF and RES.',
    weight: 1, hp: 3000, atk: 350, armor: 150, res: 5, speed: 42,
    color: 0xc0392b, dpOnKill: 2, attackInterval: 2.5, damageType: 'kinetic',
    behavior: { type: 'standard' },
  },
  {
    id: 'trooper_elite', name: 'APC Elite',
    description: 'Upgraded APC with reinforced armor.',
    weight: 2, hp: 4500, atk: 450, armor: 200, res: 10, speed: 42,
    color: 0x707070, dpOnKill: 3, attackInterval: 2.5, damageType: 'kinetic',
    behavior: { type: 'standard' },
  },
  {
    id: 'heavy', name: 'Tank',
    description: 'Heavy assault vehicle. Very high DEF.',
    weight: 3, hp: 8000, atk: 600, armor: 400, res: 10, speed: 30,
    color: 0x8e44ad, dpOnKill: 3, attackInterval: 2.5, damageType: 'kinetic',
    behavior: { type: 'standard' },
  },
  {
    id: 'heavy_elite', name: 'Tank Elite',
    description: 'Colossus-class heavy armor.',
    weight: 4, hp: 12000, atk: 800, armor: 520, res: 15, speed: 30,
    color: 0x606060, dpOnKill: 4, attackInterval: 2.5, damageType: 'kinetic',
    behavior: { type: 'standard' },
  },
  {
    id: 'drone', name: 'Drone',
    description: 'Aerial recon — flies over ground blockers.',
    weight: 0, hp: 1500, atk: 200, armor: 50, res: 0, speed: 72,
    color: 0xf39c12, dpOnKill: 1, attackInterval: 1.5, damageType: 'kinetic',
    isAerial: true, attackRange: 2.5,
    behavior: { type: 'standard' },
  },
  {
    id: 'drone_elite', name: 'Drone Elite',
    description: 'Fast aerial threat.',
    weight: 1, hp: 2200, atk: 260, armor: 80, res: 0, speed: 72,
    color: 0x909090, dpOnKill: 2, attackInterval: 1.5, damageType: 'kinetic',
    isAerial: true, attackRange: 2.5,
    behavior: { type: 'standard' },
  },
  {
    id: 'caster', name: 'Artillery Caster',
    description: 'Indirect fire — thermal damage bypasses DEF.',
    weight: 1, hp: 2500, atk: 250, armor: 80, res: 0, speed: 36,
    color: 0x9b59b6, dpOnKill: 2, attackInterval: 3.5, damageType: 'thermal',
    attackRange: 2.5,
    behavior: { type: 'standard' },
  },
  {
    id: 'caster_elite', name: 'Artillery Caster Elite',
    description: 'Heavy ordnance platform.',
    weight: 2, hp: 3800, atk: 330, armor: 100, res: 0, speed: 36,
    color: 0x808080, dpOnKill: 3, attackInterval: 3.5, damageType: 'thermal',
    attackRange: 2.5,
    behavior: { type: 'standard' },
  },
  {
    id: 'rusher', name: 'Rusher',
    description: 'Fast recon buggy — covers ground quickly.',
    weight: 0, hp: 1800, atk: 220, armor: 50, res: 0, speed: 85,
    color: 0xe67e22, dpOnKill: 1, attackInterval: 1.8, damageType: 'kinetic',
    behavior: { type: 'standard' },
  },
  {
    id: 'rusher_elite', name: 'Assault Rusher Elite',
    description: 'Up-armored fast assault vehicle.',
    weight: 1, hp: 2800, atk: 300, armor: 80, res: 0, speed: 95,
    color: 0xa0a0a0, dpOnKill: 2, attackInterval: 1.8, damageType: 'kinetic',
    behavior: { type: 'standard' },
  },
  {
    id: 'marksman', name: 'Marksman',
    description: 'Ranged kinetic attacker — threatens backline.',
    weight: 1, hp: 2400, atk: 350, armor: 80, res: 0, speed: 38,
    color: 0x27ae60, dpOnKill: 2, attackInterval: 2.8, damageType: 'kinetic',
    attackRange: 2.5,
    behavior: { type: 'standard' },
  },
  {
    id: 'marksman_elite', name: 'Marksman Elite',
    description: 'Long-range precision fire.',
    weight: 2, hp: 3600, atk: 480, armor: 120, res: 0, speed: 42,
    color: 0x808080, dpOnKill: 3, attackInterval: 2.8, damageType: 'kinetic',
    attackRange: 3.0,
    behavior: { type: 'standard' },
  },
  {
    id: 'gunship', name: 'Gunship',
    description: 'Heavy aerial platform.',
    weight: 2, hp: 5000, atk: 350, armor: 150, res: 15, speed: 45,
    color: 0xf1c40f, dpOnKill: 3, attackInterval: 2.2, damageType: 'kinetic',
    isAerial: true, attackRange: 2.0,
    behavior: { type: 'standard' },
  },
  {
    id: 'gunship_elite', name: 'Gunship Elite',
    description: 'Command gunship — boosts nearby ally ATK.',
    weight: 3, hp: 7000, atk: 450, armor: 200, res: 20, speed: 50,
    color: 0x808080, dpOnKill: 4, attackInterval: 2.2, damageType: 'kinetic',
    isAerial: true, attackRange: 2.0,
    behavior: { type: 'buffer', buffAtk: 20, buffRange: 2.0 },
  },
  {
    id: 'breacher', name: 'Breacher',
    description: 'Suicide RC car — explodes on death.',
    weight: 0, hp: 2500, atk: 150, armor: 30, res: 0, speed: 52,
    color: 0xd35400, dpOnKill: 2, attackInterval: 2.0, damageType: 'kinetic',
    behavior: { type: 'exploder', explosionDamage: 400, explosionRadius: 1.5, damageType: 'thermal' },
  },
  {
    id: 'breacher_elite', name: 'Breacher Elite',
    description: 'Heavy demolition unit. Larger blast.',
    weight: 1, hp: 4000, atk: 200, armor: 50, res: 0, speed: 55,
    color: 0x909090, dpOnKill: 3, attackInterval: 2.0, damageType: 'kinetic',
    behavior: { type: 'exploder', explosionDamage: 600, explosionRadius: 2.0, damageType: 'thermal' },
  },
  {
    id: 'phantom', name: 'Phantom',
    description: 'Stealth drone — invisible until detected.',
    weight: 1, hp: 3800, atk: 450, armor: 50, res: 15, speed: 48,
    color: 0x2c3e50, dpOnKill: 2, attackInterval: 2.0, damageType: 'kinetic',
    behavior: { type: 'stealth', detectionRange: 2.0 },
  },
  {
    id: 'phantom_elite', name: 'Phantom Elite',
    description: 'Advanced stealth unit. Harder to detect.',
    weight: 2, hp: 5500, atk: 600, armor: 80, res: 25, speed: 52,
    color: 0x505050, dpOnKill: 3, attackInterval: 2.0, damageType: 'kinetic',
    behavior: { type: 'stealth', detectionRange: 1.5 },
  },
  {
    id: 'repair', name: 'Repair Vehicle',
    description: 'Field repair — heals nearby damaged allies.',
    weight: 1, hp: 3500, atk: 200, armor: 100, res: 0, speed: 34,
    color: 0x1abc9c, dpOnKill: 2, attackInterval: 2.0, damageType: 'kinetic',
    behavior: { type: 'healer', healAmount: 200, healInterval: 3.5, healRange: 1.5 },
  },
  {
    id: 'repair_elite', name: 'Repair Elite',
    description: 'Advanced repair platform.',
    weight: 2, hp: 5000, atk: 250, armor: 150, res: 0, speed: 38,
    color: 0x808080, dpOnKill: 3, attackInterval: 2.0, damageType: 'kinetic',
    behavior: { type: 'healer', healAmount: 350, healInterval: 3.0, healRange: 2.0 },
  },
  {
    id: 'shielded', name: 'Shielded Transport',
    description: 'Protected transport — shield absorbs damage before HP.',
    weight: 2, hp: 5000, atk: 300, armor: 100, res: 0, speed: 36,
    color: 0x2980b9, dpOnKill: 2, attackInterval: 2.0, damageType: 'kinetic',
    behavior: { type: 'shielded', shieldHp: 2500 },
  },
  {
    id: 'shielded_elite', name: 'Shielded Elite',
    description: 'Heavy shielded assault.',
    weight: 3, hp: 7000, atk: 400, armor: 150, res: 0, speed: 38,
    color: 0x666666, dpOnKill: 3, attackInterval: 2.0, damageType: 'kinetic',
    behavior: { type: 'shielded', shieldHp: 4000 },
  },
  {
    id: 'carrier', name: 'Carrier Drone',
    description: 'Aerial carrier — spawns Rushers periodically.',
    weight: 2, hp: 3500, atk: 150, armor: 100, res: 10, speed: 28,
    color: 0xe91e63, dpOnKill: 3, attackInterval: 2.5, damageType: 'kinetic',
    isAerial: true,
    behavior: { type: 'summoner', spawnType: 'rusher', spawnInterval: 10, spawnCount: 1 },
  },
  {
    id: 'carrier_elite', name: 'Carrier Elite',
    description: 'Advanced carrier — spawns more enemies faster.',
    weight: 3, hp: 5000, atk: 200, armor: 150, res: 15, speed: 30,
    color: 0x808080, dpOnKill: 4, attackInterval: 2.5, damageType: 'kinetic',
    isAerial: true,
    behavior: { type: 'summoner', spawnType: 'rusher', spawnInterval: 7, spawnCount: 2 },
  },
]
