import { SkillConfig } from '../types/index'
import { RANGE_PATTERNS } from '../shared/utils/GridMath'

export const SKILLS: Record<string, SkillConfig[]> = {
  pioneer: [
    {
      id: 'pioneer_s1', name: 'Charge γ',
      description: 'Generates 12 DP immediately.',
      spRecovery: 'auto', activation: 'auto', spCost: 35, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'generateDP', amount: 12 },
    },
    {
      id: 'pioneer_s2', name: 'Sword Rain',
      description: 'Gains 12 DP, deals 170% ATK Arts damage twice to nearby enemies, stuns for 2s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 22,
      durationType: 'instant',
      effect: { type: 'special', description: 'aoe_stun' },
    },
    {
      id: 'pioneer_s3', name: 'Aerial Hammer',
      description: 'Next attack deals 340% ATK physical damage to adjacent enemies, gains 3 DP. Stores 3 charges.',
      spRecovery: 'auto', activation: 'auto', spCost: 10, spInitial: 0,
      charges: 3, durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 3.4 },
    },
  ],
  charger: [
    {
      id: 'charger_s1', name: 'Swift Strike γ',
      description: 'ATK +45%, ASPD +45. Lasts 35s.',
      spRecovery: 'auto', activation: 'auto', spCost: 35, spInitial: 0,
      durationType: 'duration', duration: 35,
      effect: { type: 'statBuff', atkMultiplier: 1.45, aspdBonus: 45 },
    },
    {
      id: 'charger_s2', name: 'High-Impact Assault',
      description: 'Next attack deals 200% ATK and strikes twice. Stores up to 3 charges.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      charges: 3, durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2, hitCount: 2 },
    },
    {
      id: 'charger_s3', name: 'Locked Breech Burst',
      description: 'ATK +120%, DEF +120%, Block +1, attacks hit 3 times. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 25,
      durationType: 'duration', duration: 20,
      effect: { type: 'statBuff', atkMultiplier: 2.2, defMultiplier: 2.2, blockBonus: 1 },
    },
  ],
  fighter: [
    {
      id: 'fighter_s1', name: 'Left Hook',
      description: 'Next attack deals 180% ATK and stuns for 1s.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 1.8 },
    },
    {
      id: 'fighter_s2', name: 'Stance of the Cautious',
      description: 'DEF +150%, Block +1, restores 7% HP per second. Toggle on/off.',
      spRecovery: 'auto', activation: 'toggle', spCost: 5, spInitial: 0,
      durationType: 'toggle',
      effect: { type: 'statToggle', defMultiplier: 2.5, blockBonus: 1, hpRegenPerSecond: { percent: 7 } },
    },
    {
      id: 'fighter_s3', name: 'Stance of the Mountain',
      description: 'ATK +80%, attacks hit all enemies in melee range. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 30, spInitial: 10,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.8, targetCount: 99 },
    },
  ],
  arts_fighter: [
    {
      id: 'arts_fighter_s1', name: 'Flame Scimitar',
      description: 'Next attack deals 250% ATK as thermal damage.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2.5 },
    },
    {
      id: 'arts_fighter_s2', name: 'Soul Eruption',
      description: 'ATK +100%, attacks hit up to 3 targets. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 30, spInitial: 10,
      durationType: 'duration', duration: 25,
      effect: { type: 'statBuff', atkMultiplier: 2, defMultiplier: 1.5 },
    },
    {
      id: 'arts_fighter_s3', name: 'Twilight',
      description: 'ATK +330%, attack range expands, deals true damage. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 75, spInitial: 27,
      durationType: 'duration', duration: 25,
      effect: { type: 'enhanceAttack', atkMultiplier: 4.3, trueDamage: true },
    },
  ],
  centurion_guard: [
    {
      id: 'centurion_s1', name: 'Sweeping Strike',
      description: 'Next attack deals 180% ATK to all blocked enemies.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 1.8 },
    },
    {
      id: 'centurion_s2', name: 'Bone Fracture',
      description: 'Cannot be reduced below 1 HP, ATK +80%. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 50, spInitial: 20,
      durationType: 'duration', duration: 15,
      effect: { type: 'survival', duration: 15 },
    },
    {
      id: 'centurion_s3', name: 'Boiling Burst',
      description: 'ATK +50%, attacks deal AoE damage around self. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 25,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.5, targetCount: 99 },
    },
  ],
  swordmaster: [
    {
      id: 'swordmaster_s1', name: 'Double Strike',
      description: 'Next attack fires 2 hits at 140% ATK each.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 1.4, hitCount: 2 },
    },
    {
      id: 'swordmaster_s2', name: 'Chi Xiao - Unsheath',
      description: 'Deals 500% ATK to target enemy.',
      spRecovery: 'auto', activation: 'manual', spCost: 30, spInitial: 10,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 5 },
    },
    {
      id: 'swordmaster_s3', name: 'Chi Xiao - Shadowless',
      description: 'ATK +60%, attacks ignore 50% DEF. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 45, spInitial: 15,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.6, defIgnore: 50 },
    },
  ],
  lord_guard: [
    {
      id: 'lord_s1', name: 'Power Strike γ',
      description: 'Next ranged attack deals 210% ATK.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2.1 },
    },
    {
      id: 'lord_s2', name: 'Resting Regeneration',
      description: 'DEF +100%, restores 6% HP per second, attacks become melee only. Toggle on/off.',
      spRecovery: 'auto', activation: 'toggle', spCost: 5, spInitial: 0,
      durationType: 'toggle',
      effect: { type: 'statToggle', defMultiplier: 2, hpRegenPerSecond: { percent: 6 }, meleeOnly: true },
    },
    {
      id: 'lord_s3', name: 'Truesilver Slash',
      description: 'ATK +200%, attacks hit up to 6 targets, DEF -70%, attack range expands. Lasts 30s.',
      spRecovery: 'auto', activation: 'manual', spCost: 90, spInitial: 75,
      durationType: 'duration', duration: 30,
      effect: { type: 'enhanceAttack', atkMultiplier: 3, targetCount: 6 },
    },
  ],
  instructor_guard: [
    {
      id: 'instructor_s1', name: 'Spur',
      description: 'Next attack buffs nearest ally ATK +35% for 5s.',
      spRecovery: 'auto', activation: 'auto', spCost: 5, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'buffAlly', atkMultiplier: 1.35, duration: 5 },
    },
    {
      id: 'instructor_s2', name: 'Battle Cry',
      description: 'All allies in range gain ATK +30%. Lasts 30s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 30,
      effect: { type: 'buffAlly', atkMultiplier: 1.3, duration: 30 },
    },
    {
      id: 'instructor_s3', name: "Vanguard's Pride",
      description: 'Self ATK +80%, all melee allies gain ATK +50%. Lasts 30s.',
      spRecovery: 'auto', activation: 'manual', spCost: 50, spInitial: 25,
      durationType: 'duration', duration: 30,
      effect: { type: 'statBuff', atkMultiplier: 1.8 },
    },
  ],
  soloblade: [
    {
      id: 'soloblade_s1', name: 'Crescent Moon',
      description: 'Next attack deals 175% ATK, hits twice.',
      spRecovery: 'offensive', activation: 'auto', spCost: 2, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 1.75, hitCount: 2 },
    },
    {
      id: 'soloblade_s2', name: 'Half Moon',
      description: 'ATK +80%, attacks hit twice, DEF +80%. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 35, spInitial: 15,
      durationType: 'duration', duration: 25,
      effect: { type: 'statBuff', atkMultiplier: 1.8, defMultiplier: 1.8 },
    },
    {
      id: 'soloblade_s3', name: 'Full Moon',
      description: 'ATK +100%, attacks hit up to 3 targets. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 50, spInitial: 20,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 2, targetCount: 3 },
    },
  ],
  reaper: [
    {
      id: 'reaper_s1', name: 'Soul Drain',
      description: 'ATK +30%, heal per enemy hit doubled. Activates automatically. Lasts 20s.',
      spRecovery: 'auto', activation: 'auto', spCost: 5, spInitial: 0,
      durationType: 'duration', duration: 20,
      effect: { type: 'statBuff', atkMultiplier: 1.3, healOnAttackMultiplier: 2 },
    },
    {
      id: 'reaper_s2', name: 'Graveyard Mist',
      description: 'ATK +60%, attacks hit all enemies in range, heal multiplier +50%. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 35, spInitial: 10,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.6, targetCount: 99 },
    },
    {
      id: 'reaper_s3', name: "Reaper's Scythe",
      description: "ATK +120%, attack range expands, heal on hit +100%. Lasts 12s.",
      spRecovery: 'auto', activation: 'manual', spCost: 50, spInitial: 20,
      durationType: 'duration', duration: 12,
      effect: { type: 'enhanceAttack', atkMultiplier: 2.2, targetCount: 99 },
    },
  ],
  crusher: [
    {
      id: 'crusher_s1', name: 'Crush',
      description: 'Next attack deals 200% ATK as true damage.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2, trueDamage: true },
    },
    {
      id: 'crusher_s2', name: 'Shatter',
      description: 'ATK +40%, attacks deal true splash damage in 1-tile radius. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 10,
      durationType: 'duration', duration: 20,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.4, trueDamage: true, splash: { radius: 1, damageMultiplier: 1 } },
    },
    {
      id: 'crusher_s3', name: 'Annihilate',
      description: 'ATK +120%, attacks hit all enemies in melee range as true damage. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 55, spInitial: 25,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 2.2, trueDamage: true, targetCount: 99 },
    },
  ],
  earthshaker: [
    {
      id: 'earthshaker_s1', name: 'Shockwave',
      description: 'Next attack deals 200% ATK in a 3-tile line.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2, targetCount: 99 },
    },
    {
      id: 'earthshaker_s2', name: 'Tremor',
      description: 'ATK +30%, attacks trigger 1-tile splash around target. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 35, spInitial: 10,
      durationType: 'duration', duration: 20,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.3, splash: { radius: 1, damageMultiplier: 1 } },
    },
    {
      id: 'earthshaker_s3', name: 'Lotus Hammer',
      description: 'ATK +80%, attacks hit all enemies in 2-tile radius. Lasts 12s.',
      spRecovery: 'auto', activation: 'manual', spCost: 50, spInitial: 20,
      durationType: 'duration', duration: 12,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.8, targetCount: 99, splash: { radius: 2, damageMultiplier: 1 } },
    },
  ],
  protector: [
    {
      id: 'protector_s1', name: 'Warpath',
      description: 'DEF +80%. Lasts 30s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 20,
      durationType: 'duration', duration: 30,
      effect: { type: 'statBuff', defMultiplier: 1.8 },
    },
    {
      id: 'protector_s2', name: 'Shell Defense',
      description: 'DEF +200%, Block +1, restores 6% HP per second. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 50, spInitial: 20,
      durationType: 'duration', duration: 20,
      effect: { type: 'statBuff', defMultiplier: 3, blockBonus: 1, hpRegenPerSecond: { percent: 6 } },
    },
    {
      id: 'protector_s3', name: 'Self-Sustain',
      description: 'When HP falls below 40%, automatically gain DEF +100% and ATK +50%. Lasts 15s.',
      spRecovery: 'auto', activation: 'auto', spCost: 40, spInitial: 0,
      durationType: 'duration', duration: 15,
      effect: { type: 'special', description: 'conditional_statbuff' },
    },
  ],
  guardian: [
    {
      id: 'guardian_s1', name: 'First Aid',
      description: 'Next heal restores 180% ATK on an ally below 50% HP. Stores 3 charges.',
      spRecovery: 'auto', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'heal', amountMultiplier: 1.8, range: 'ally' },
      skillRangePattern: RANGE_PATTERNS.surrounding8,
      charges: 3,
    },
    {
      id: 'guardian_s2', name: 'Medicine Dispensing',
      description: 'Heals all allies in range for 140% ATK.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'instant',
      effect: { type: 'heal', amountMultiplier: 1.4, range: 'allies' },
    },
    {
      id: 'guardian_s3', name: 'Calcification',
      description: 'DEF +80%, heals all allies in range every 2s, enemies in range take 55% more thermal damage, slowed. Lasts 30s.',
      spRecovery: 'auto', activation: 'manual', spCost: 80, spInitial: 70,
      durationType: 'duration', duration: 30,
      effect: { type: 'statBuff', defMultiplier: 1.8 },
    },
  ],
  fortress_defender: [
    {
      id: 'fortress_s1', name: 'Shelling',
      description: 'Next ranged attack deals 180% splash damage in 1-tile radius.',
      spRecovery: 'offensive', activation: 'auto', spCost: 5, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 1.8, splash: { radius: 1, damageMultiplier: 1 } },
    },
    {
      id: 'fortress_s2', name: 'Bombardment',
      description: 'Ranged attacks hit all enemies in 2-tile radius. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 25,
      effect: { type: 'enhanceAttack', targetCount: 99, splash: { radius: 2, damageMultiplier: 1 } },
    },
    {
      id: 'fortress_s3', name: 'Artillery',
      description: 'ATK +80%, attacks hit all enemies in range. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 55, spInitial: 25,
      durationType: 'duration', duration: 20,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.8, targetCount: 99 },
    },
  ],
  sentry_protector: [
    {
      id: 'sentry_s1', name: 'Discharge',
      description: 'ATK +50%, ASPD +30. Lasts 25s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 30, spInitial: 10,
      durationType: 'duration', duration: 25,
      effect: { type: 'statBuff', atkMultiplier: 1.5, aspdBonus: 30 },
    },
    {
      id: 'sentry_s2', name: 'Taser Strike',
      description: 'Next attack deals 250% ATK and stuns target for 1s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 6, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2.5, binds: true },
    },
    {
      id: 'sentry_s3', name: 'Sentry Mode',
      description: 'ATK +80%, DEF +50%, attacks hit all enemies in range. Lasts 30s.',
      spRecovery: 'auto', activation: 'manual', spCost: 75, spInitial: 50,
      durationType: 'duration', duration: 30,
      effect: { type: 'statToggle', atkMultiplier: 1.8, defMultiplier: 1.5, attackAllBlocked: true },
    },
  ],
  arts_protector: [
    {
      id: 'arts_protector_s1', name: 'Arts Infusion',
      description: 'ATK +50%. Lasts 30s.',
      spRecovery: 'auto', activation: 'manual', spCost: 35, spInitial: 20,
      durationType: 'duration', duration: 30,
      effect: { type: 'statBuff', atkMultiplier: 1.5 },
    },
    {
      id: 'arts_protector_s2', name: 'Thermal Strike',
      description: 'Next attack deals 200% ATK as true damage. Stuns target for 1s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 5, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2, trueDamage: true, binds: true },
    },
    {
      id: 'arts_protector_s3', name: 'Arts Bulwark',
      description: 'ATK +80%, blocks +1. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 70, spInitial: 50,
      durationType: 'duration', duration: 25,
      effect: { type: 'statBuff', atkMultiplier: 1.8, blockBonus: 1 },
    },
  ],
  juggernaut: [
    {
      id: 'juggernaut_s1', name: 'DEF Up γ',
      description: 'DEF +100%. Lasts 40s.',
      spRecovery: 'auto', activation: 'manual', spCost: 30, spInitial: 15,
      durationType: 'duration', duration: 40,
      effect: { type: 'statBuff', defMultiplier: 2 },
    },
    {
      id: 'juggernaut_s2', name: 'Indomitable',
      description: 'When HP falls below 30%, gain a shield equal to 30% of max HP.',
      spRecovery: 'auto', activation: 'auto', spCost: 10, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'survival', shieldPercent: 30 },
    },
    {
      id: 'juggernaut_s3', name: 'Unstoppable',
      description: 'ATK +150%, DEF +100%, attacks hit all blocked enemies. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 55, spInitial: 20,
      durationType: 'duration', duration: 15,
      effect: { type: 'statBuff', atkMultiplier: 2.5, defMultiplier: 2 },
    },
  ],
  core_caster: [
    {
      id: 'core_caster_s1', name: 'Duetto',
      description: 'ASPD +60, second+ use also grants ATK +60%. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 35, spInitial: 25,
      durationType: 'duration', duration: 25,
      effect: { type: 'statBuff', aspdBonus: 60 },
    },
    {
      id: 'core_caster_s2', name: 'Ignition',
      description: 'Next attack deals 370% ATK as thermal damage. Stores 3 charges.',
      spRecovery: 'auto', activation: 'auto', spCost: 5, spInitial: 0,
      charges: 3, durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 3.7 },
    },
    {
      id: 'core_caster_s3', name: 'Volcano',
      description: 'ATK +130%, attacks deal splash damage in 1-tile radius, range extended by +1 tile. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 80, spInitial: 55,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 2.3, splash: { radius: 1, damageMultiplier: 1 } },
    },
  ],
  blast_caster: [
    {
      id: 'blast_caster_s1', name: 'Fanaticism',
      description: 'ATK +20%, ASPD +80. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 20,
      durationType: 'duration', duration: 20,
      effect: { type: 'statBuff', atkMultiplier: 1.2, aspdBonus: 80 },
    },
    {
      id: 'blast_caster_s2', name: 'Pyroclasm',
      description: 'Next attack deals 250% ATK as thermal damage. Stores 3 charges.',
      spRecovery: 'auto', activation: 'auto', spCost: 7, spInitial: 0,
      charges: 3, durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2.5 },
    },
    {
      id: 'blast_caster_s3', name: 'Scorched Earth',
      description: 'ATK +100%, leaves burning ground dealing 30% ATK per second for 5s. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 60, spInitial: 25,
      durationType: 'duration', duration: 20,
      effect: { type: 'enhanceAttack', atkMultiplier: 2 },
    },
  ],
  splash_caster: [
    {
      id: 'splash_caster_s1', name: 'ATK Up γ',
      description: 'ATK +100%. Lasts 30s.',
      spRecovery: 'auto', activation: 'manual', spCost: 30, spInitial: 15,
      durationType: 'duration', duration: 30,
      effect: { type: 'statBuff', atkMultiplier: 2 },
    },
    {
      id: 'splash_caster_s2', name: 'Fire of Heaven',
      description: 'Deals 240% ATK thermal damage to all enemies in a large area, stuns for 1s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2.4, splash: { radius: 2, damageMultiplier: 1 } },
    },
    {
      id: 'splash_caster_s3', name: 'Meteor Storm',
      description: 'ATK +150%, ASPD +50, attacks call down splash damage. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 80, spInitial: 40,
      durationType: 'duration', duration: 25,
      effect: { type: 'statBuff', atkMultiplier: 2.5, aspdBonus: 50 },
    },
  ],
  chain_caster: [
    {
      id: 'chain_caster_s1', name: 'Focus γ',
      description: 'ATK +40%, ASPD +4. Lasts 10s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 20, spInitial: 10,
      durationType: 'duration', duration: 10,
      effect: { type: 'statBuff', atkMultiplier: 1.4, aspdBonus: 4 },
    },
    {
      id: 'chain_caster_s2', name: 'Chain Lightning',
      description: 'ATK +70%, chains to 4 targets with no damage falloff. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 25,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.7 },
    },
    {
      id: 'chain_caster_s3', name: 'Lightning Storm',
      description: 'ATK +130%, chains to all enemies in range, ASPD +50. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 60, spInitial: 25,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 2.3 },
    },
  ],
  sniper: [
    {
      id: 'sniper_s1', name: 'Power Strike γ',
      description: 'Next attack deals 210% ATK.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2.1 },
    },
    {
      id: 'sniper_s2', name: 'Focus γ',
      description: 'ATK +60%, range expands. Lasts 10s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 25, spInitial: 10,
      durationType: 'duration', duration: 10,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.6 },
    },
    {
      id: 'sniper_s3', name: 'Texas Ranger',
      description: 'ATK +130%, ASPD +50, attacks hit 2 targets. Lasts 15s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 2.3, aspdBonus: 50, hitCount: 2 },
    },
  ],
  deadeye: [
    {
      id: 'deadeye_s1', name: 'Power Strike γ',
      description: 'Next attack deals 210% ATK.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2.1 },
    },
    {
      id: 'deadeye_s2', name: 'Snipe',
      description: 'Deals 400% ATK to target enemy.',
      spRecovery: 'offensive', activation: 'manual', spCost: 25, spInitial: 10,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 4 },
    },
    {
      id: 'deadeye_s3', name: 'Scopes',
      description: 'ATK +70%, range expands, targets lowest DEF enemy. Lasts 15s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 30, spInitial: 10,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.7 },
    },
  ],
  heavyshooter: [
    {
      id: 'heavyshooter_s1', name: 'Power Strike γ',
      description: 'Next attack deals 210% ATK.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2.1 },
    },
    {
      id: 'heavyshooter_s2', name: 'Marksmanship γ',
      description: 'ATK +50%, ASPD +30. Lasts 20s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 28, spInitial: 10,
      durationType: 'duration', duration: 20,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.5, aspdBonus: 30 },
    },
    {
      id: 'heavyshooter_s3', name: 'Shattergun',
      description: 'ATK +80%, attacks hit all enemies in range. Lasts 15s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 45, spInitial: 15,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.8, targetCount: 99 },
    },
  ],
  artilleryman: [
    {
      id: 'artilleryman_s1', name: 'Power Strike γ',
      description: 'Next attack deals 210% ATK.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2.1 },
    },
    {
      id: 'artilleryman_s2', name: 'Explosive Bullets',
      description: 'ATK +80%, attacks deal AoE damage. Lasts 15s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 30, spInitial: 10,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.8, splash: { radius: 1, damageMultiplier: 1 } },
    },
    {
      id: 'artilleryman_s3', name: 'Hailstorm',
      description: 'ATK +140%, attacks hit all enemies in range with splash. Lasts 20s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 48, spInitial: 15,
      durationType: 'duration', duration: 20,
      effect: { type: 'enhanceAttack', atkMultiplier: 2.4, targetCount: 99, splash: { radius: 1, damageMultiplier: 0.8 } },
    },
  ],
  decel_binder: [
    {
      id: 'decel_binder_s1', name: 'Focus γ',
      description: 'ATK +40%, ASPD +4. Lasts 10s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 20, spInitial: 10,
      durationType: 'duration', duration: 10,
      effect: { type: 'statBuff', atkMultiplier: 1.4, aspdBonus: 4 },
    },
    {
      id: 'decel_binder_s2', name: 'Speed Up γ',
      description: 'All allies in range gain ATK +8% and ASPD +4. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 35, spInitial: 10,
      durationType: 'duration', duration: 15,
      effect: { type: 'buffAlly', atkMultiplier: 1.08, aspdBonus: 4, duration: 15 },
    },
    {
      id: 'decel_binder_s3', name: 'Particle Field',
      description: 'ATK +60%, attacks slow enemies by 70% for 1.5s, ASPD +40. Lasts 25s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 50, spInitial: 15,
      durationType: 'duration', duration: 25,
      effect: { type: 'debuffEnemies', slowFactor: 0.7, duration: 25 },
    },
  ],
  bard_supporter: [
    {
      id: 'bard_s1', name: 'Inspire',
      description: 'All allies in range gain ATK +20%. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 30, spInitial: 10,
      durationType: 'duration', duration: 25,
      effect: { type: 'buffAlly', atkMultiplier: 1.2, duration: 25 },
    },
    {
      id: 'bard_s2', name: 'Ballad',
      description: 'All allies in range gain ATK +40% and DEF +30%. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 20,
      effect: { type: 'buffAlly', atkMultiplier: 1.4, defMultiplier: 1.3, duration: 20 },
    },
    {
      id: 'bard_s3', name: 'Requiem',
      description: 'All allies in range gain ATK +80% and restore 5% HP per second. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 60, spInitial: 25,
      durationType: 'duration', duration: 15,
      effect: { type: 'buffAlly', atkMultiplier: 1.8, hpRegen: 5, duration: 15 },
    },
  ],
  medic_st: [
    {
      id: 'medic_st_s1', name: 'Cure γ',
      description: 'Next heal restores 180% ATK.',
      spRecovery: 'auto', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'heal', amountMultiplier: 1.8, range: 'ally' },
    },
    {
      id: 'medic_st_s2', name: 'Healing γ',
      description: 'ATK +50%, heals 2 targets. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 35, spInitial: 10,
      durationType: 'duration', duration: 25,
      effect: { type: 'statBuff', aspdBonus: 60 },
    },
    {
      id: 'medic_st_s3', name: "Nightingale's Blessing",
      description: 'ATK +100%, heals all allies in range for 250% ATK.',
      spRecovery: 'auto', activation: 'manual', spCost: 50, spInitial: 20,
      durationType: 'instant',
      effect: { type: 'heal', amountMultiplier: 2.5, range: 'allies' },
    },
  ],
  incantation_medic: [
    {
      id: 'incantation_medic_s1', name: 'Power Strike γ',
      description: 'Next attack deals 210% ATK as thermal damage.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2.1 },
    },
    {
      id: 'incantation_medic_s2', name: 'Fire Within',
      description: 'ATK +60%, attacks hit 2 enemies, heals 1 ally per attack. Lasts 20s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 30, spInitial: 10,
      durationType: 'duration', duration: 20,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.6 },
    },
    {
      id: 'incantation_medic_s3', name: 'Flame of Life',
      description: 'ATK +120%, attacks hit 3 enemies, heals 2 allies per attack. Lasts 25s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 55, spInitial: 15,
      durationType: 'duration', duration: 25,
      effect: { type: 'enhanceAttack', atkMultiplier: 2.2 },
    },
  ],
  medic_multi: [
    {
      id: 'medic_multi_s1', name: 'Cure γ',
      description: 'Next heal restores 180% ATK.',
      spRecovery: 'auto', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'heal', amountMultiplier: 1.8, range: 'ally' },
    },
    {
      id: 'medic_multi_s2', name: 'Healing γ',
      description: 'ATK +50%, heals up to 3 targets. Lasts 30s.',
      spRecovery: 'auto', activation: 'manual', spCost: 28, spInitial: 10,
      durationType: 'duration', duration: 30,
      effect: { type: 'statBuff', healOnAttackMultiplier: 1.5 },
    },
    {
      id: 'medic_multi_s3', name: "Silence's Remedy",
      description: 'Range +1, all allies in range heal for 100% ATK every 2s. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 50, spInitial: 25,
      durationType: 'duration', duration: 20,
      effect: { type: 'heal', amountMultiplier: 1, range: 'allies' },
    },
  ],
  chain_medic: [
    {
      id: 'chain_medic_s1', name: 'Chain Burst',
      description: 'Next heal jumps to +2 more allies (5 total), no falloff for first bounce.',
      spRecovery: 'auto', activation: 'auto', spCost: 5, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'heal', amountMultiplier: 1.5, range: 'ally' },
    },
    {
      id: 'chain_medic_s2', name: 'Resilient Link',
      description: 'ATK +40%, healing chain falloff reduced to 15%. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 30, spInitial: 10,
      durationType: 'duration', duration: 25,
      effect: { type: 'statBuff', atkMultiplier: 1.4 },
    },
    {
      id: 'chain_medic_s3', name: 'Vital Surge',
      description: 'ATK +80%, chain jumps to 5 allies. Restores 30% of max HP to all in range. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 55, spInitial: 20,
      durationType: 'duration', duration: 20,
      effect: { type: 'statBuff', atkMultiplier: 1.8 },
    },
  ],
  roadblock: [],
  pusher: [
    {
      id: 'pusher_s1', name: 'Barrel Burst',
      description: 'Next attack pushes target away 1 tile, stuns 1.5s if hits wall. Auto-triggers.',
      spRecovery: 'auto', activation: 'auto', spCost: 6, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'special', description: 'auto_push_stun_wall' },
    },
    {
      id: 'pusher_s2', name: 'Hydraulics Mode',
      description: 'Permanent: ATK +50%, range +1, splash radius 1, all attacks push 1 tile.',
      spRecovery: 'auto', activation: 'manual', spCost: 90, spInitial: 45,
      durationType: 'unlimited',
      effect: { type: 'enhanceAttack', atkMultiplier: 1.5, splash: { radius: 1, damageMultiplier: 1 } },
    },
    {
      id: 'pusher_s3', name: 'Liquid Nitrogen Cannon',
      description: 'Deploys a cannon pushing all enemies in range, deals 280% ATK damage and slows for 4s.',
      spRecovery: 'auto', activation: 'manual', spCost: 70, spInitial: 25,
      durationType: 'instant',
      effect: { type: 'displace', direction: 'away', tiles: 3, radius: 3 },
    },
  ],
  puller: [
    {
      id: 'puller_s1', name: "Waterless Parting of the Great Ocean",
      description: 'Auto-trigger. Next attack pulls target toward you, dealing 210% ATK as Physical damage. Stores 3 charges.',
      spRecovery: 'auto', activation: 'auto', spCost: 4, spInitial: 0,
      charges: 3, durationType: 'instant',
      effect: { type: 'special', description: 'auto_pull_arts' },
    },
    {
      id: 'puller_s2', name: "Waterless Grasp of the Raging Seas",
      description: 'Pulls all enemies in 3-tile frontal line toward you, deals 220% ATK as physical damage.',
      spRecovery: 'auto', activation: 'manual', spCost: 15, spInitial: 5,
      durationType: 'instant',
      effect: { type: 'special', description: 'line_pull_damage' },
    },
    {
      id: 'puller_s3', name: 'Dance of the Shattered Maelstrom',
      description: 'Binds furthest enemy, creates whirlpool pulling enemies every 1.5s for 8s, slows 50%.',
      spRecovery: 'auto', activation: 'manual', spCost: 35, spInitial: 15,
      durationType: 'duration', duration: 8,
      effect: { type: 'special', description: 'maelstrom_pull_slow' },
    },
  ],
  mech_accord_caster: [
    {
      id: 'mech_accord_s1', name: 'Drone Overclock',
      description: 'ASPD +50, ATK +25%. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 10,
      durationType: 'duration', duration: 25,
      effect: { type: 'statBuff', aspdBonus: 50, atkMultiplier: 1.25 },
    },
    {
      id: 'mech_accord_s2', name: 'Volley Fire',
      description: 'Next attack deals 180% ATK Arts damage and strikes 3 times. Stores up to 2 charges.',
      spRecovery: 'offensive', activation: 'auto', spCost: 6, spInitial: 0,
      charges: 2, durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 1.8, hitCount: 3 },
    },
    {
      id: 'mech_accord_s3', name: 'Swarm Surge',
      description: 'Drone +2, ATK +60%, attacks slow enemies by 50% for 0.5s. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 50, spInitial: 15,
      durationType: 'duration', duration: 25,
      effect: { type: 'statBuff', atkMultiplier: 1.6 },
    },
  ],
  spreadshooter: [
    {
      id: 'spreadshooter_s1', name: 'Power Strike γ',
      description: 'Next attack deals 210% ATK.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2.1 },
    },
    {
      id: 'spreadshooter_s2', name: 'Scatter Blast',
      description: 'ATK +60%, ASPD +30. Lasts 20s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 30, spInitial: 10,
      durationType: 'duration', duration: 20,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.6, aspdBonus: 30 },
    },
    {
      id: 'spreadshooter_s3', name: 'Drum-fed Spree',
      description: 'ATK +40%, ASPD +60, range extended by 1 row. Lasts 15s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.4, aspdBonus: 60 },
      skillRangePattern: [[-3,-1],[-3,0],[-3,1],[-2,-1],[-2,0],[-2,1],[-1,-1],[-1,0],[-1,1],[0,0]],
    },
  ],
  besieger: [
    {
      id: 'besieger_s1', name: 'Power Strike γ',
      description: 'Next attack deals 210% ATK.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2.1 },
    },
    {
      id: 'besieger_s2', name: 'Bombardment',
      description: 'ATK +80%, ASPD +20. Lasts 20s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 30, spInitial: 10,
      durationType: 'duration', duration: 20,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.8, aspdBonus: 20 },
    },
    {
      id: 'besieger_s3', name: 'Siege Mode',
      description: 'ATK +100%, range extended by +1 column to each side. Lasts 15s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 45, spInitial: 20,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 2.0 },
      skillRangePattern: [[-4,-2],[-4,-1],[-4,0],[-4,1],[-4,2],[-3,-3],[-3,-2],[-3,-1],[-3,0],[-3,1],[-3,2],[-3,3],[-2,-3],[-2,-2],[-2,-1],[-2,0],[-2,1],[-2,2],[-2,3],[0,0]],
    },
  ],
  flinger: [
    {
      id: 'flinger_s1', name: 'Power Strike γ',
      description: 'Next attack deals 210% ATK.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2.1 },
    },
    {
      id: 'flinger_s2', name: 'Concussive Blast',
      description: 'ATK +50%, ASPD +30. Lasts 20s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 30, spInitial: 10,
      durationType: 'duration', duration: 20,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.5, aspdBonus: 30 },
    },
    {
      id: 'flinger_s3', name: 'Boomerang Volley',
      description: 'ATK +80%, shockwave radius +1. Lasts 15s.',
      spRecovery: 'offensive', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.8, splash: { radius: 2, damageMultiplier: 0.5 } },
    },
  ],
  executor: [
    {
      id: 'executor_s1', name: 'Rapid Response',
      description: 'DEF +80%, ATK +30%. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 20, spInitial: 5,
      durationType: 'duration', duration: 15,
      effect: { type: 'statBuff', defMultiplier: 1.8, atkMultiplier: 1.3 },
    },
    {
      id: 'executor_s2', name: 'Execution',
      description: 'ATK +150%. Next attack deals 2.5x damage.',
      spRecovery: 'auto', activation: 'auto', spCost: 8, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2.5 },
    },
  ],
}
