import { SkillConfig } from '../types/index'

export const SKILLS: Record<string, SkillConfig[]> = {
  pioneer: [
    {
      id: 'pioneer_s1', name: 'Supply',
      description: 'Generates 12 DP immediately.',
      spRecovery: 'auto', activation: 'auto', spCost: 33, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'generateDP', amount: 12 },
    },
    {
      id: 'pioneer_s2', name: 'Sword Rain',
      description: 'Deals 300% AoE damage in 2-tile radius around self, stuns enemies for 2s.',
      spRecovery: 'auto', activation: 'manual', spCost: 30, spInitial: 10,
      durationType: 'instant',
      effect: { type: 'special', description: 'aoe_stun' },
    },
    {
      id: 'pioneer_s3', name: 'Aerial Hammer',
      description: 'ATK +60%, attacks deal splash damage in 1-tile radius, generates 1 DP on kill. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 45, spInitial: 15,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.6, splash: { radius: 1, damageMultiplier: 1 } },
    },
  ],
  charger: [
    {
      id: 'charger_s1', name: 'Charging',
      description: 'Next attack deals 200% ATK.',
      spRecovery: 'auto', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2 },
    },
    {
      id: 'charger_s2', name: 'End of Line',
      description: 'ATK +50%, generates 1 DP on each attack hit. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 35, spInitial: 10,
      durationType: 'duration', duration: 20,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.5 },
    },
    {
      id: 'charger_s3', name: 'Mandragora',
      description: 'ATK +100%, attacks deal true damage, unit cannot be blocked. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 50, spInitial: 20,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 2, trueDamage: true },
    },
  ],
  fighter: [
    {
      id: 'fighter_s1', name: 'Power Strike',
      description: 'Next attack deals 210% ATK.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2.1 },
    },
    {
      id: 'fighter_s2', name: 'Sweeping Stance',
      description: 'ATK +50%, Block +1, attacks hit all blocked enemies, restores 5% HP per second. Toggle on/off.',
      spRecovery: 'auto', activation: 'toggle', spCost: 8, spInitial: 0,
      durationType: 'toggle',
      effect: { type: 'statToggle', atkMultiplier: 1.5, blockBonus: 1, attackAllBlocked: true, hpRegenPerSecond: { percent: 5 } },
    },
    {
      id: 'fighter_s3', name: 'Collapse',
      description: 'ATK +80%, attacks hit all enemies in melee range. Lasts 12s.',
      spRecovery: 'auto', activation: 'manual', spCost: 50, spInitial: 20,
      durationType: 'duration', duration: 12,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.8, targetCount: 99 },
    },
  ],
  arts_fighter: [
    {
      id: 'arts_fighter_s1', name: 'Arts Strike',
      description: 'Next attack deals 230% ATK as thermal damage.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2.3 },
    },
    {
      id: 'arts_fighter_s2', name: 'Shadow Strike',
      description: 'ATK +40%, attacks splash in 1-tile radius as thermal damage. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 35, spInitial: 10,
      durationType: 'duration', duration: 20,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.4, splash: { radius: 1, damageMultiplier: 1 } },
    },
    {
      id: 'arts_fighter_s3', name: 'Twilight',
      description: 'ATK +150%, attacks deal true damage. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 60, spInitial: 25,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 2.5, trueDamage: true },
    },
  ],
  centurion_guard: [
    {
      id: 'centurion_s1', name: 'Sweeping Strike',
      description: 'Next attack deals 180% ATK to all blocked enemies.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 1.8 },
    },
    {
      id: 'centurion_s2', name: 'Chain Saw',
      description: 'ATK +50%, attacks deal AoE damage around self. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 25,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.5, targetCount: 99 },
    },
    {
      id: 'centurion_s3', name: 'Bone Fracture',
      description: 'ATK +80%, unit cannot be reduced below 1 HP. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 50, spInitial: 20,
      durationType: 'duration', duration: 15,
      effect: { type: 'survival', duration: 15 },
    },
  ],
  swordmaster: [
    {
      id: 'swordmaster_s1', name: 'Double Strike',
      description: 'Next attack fires 3 hits at 140% ATK each.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 1.4, hitCount: 3 },
    },
    {
      id: 'swordmaster_s2', name: 'Sword Heart',
      description: 'Deals 500% ATK to target enemy.',
      spRecovery: 'auto', activation: 'manual', spCost: 30, spInitial: 10,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 5 },
    },
    {
      id: 'swordmaster_s3', name: 'Radiant Edge',
      description: 'ATK +60%, attacks ignore 50% DEF. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 45, spInitial: 15,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.6, defIgnore: 50 },
    },
  ],
  lord_guard: [
    {
      id: 'lord_s1', name: 'Power Shot',
      description: 'Next ranged attack deals 210% ATK.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2.1 },
    },
    {
      id: 'lord_s2', name: 'Rules of Survival',
      description: 'DEF +100%, restores 4% HP per second, attacks become melee only. Toggle on/off.',
      spRecovery: 'auto', activation: 'toggle', spCost: 5, spInitial: 0,
      durationType: 'toggle',
      effect: { type: 'statToggle', defMultiplier: 2, hpRegenPerSecond: { percent: 4 }, meleeOnly: true },
    },
    {
      id: 'lord_s3', name: 'Truesilver Slash',
      description: 'ATK +200%, attacks hit up to 6 targets, DEF -70%, attack range expands. Lasts 30s.',
      spRecovery: 'auto', activation: 'manual', spCost: 75, spInitial: 50,
      durationType: 'duration', duration: 30,
      effect: { type: 'enhanceAttack', atkMultiplier: 3, targetCount: 6 },
    },
  ],
  instructor_guard: [
    {
      id: 'instructor_s1', name: 'Command',
      description: 'Next attack buffs nearest ally ATK +30% for 5s.',
      spRecovery: 'auto', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'buffAlly', atkMultiplier: 1.3, duration: 5 },
    },
    {
      id: 'instructor_s2', name: 'War Cry',
      description: 'All allies in range gain ATK +40%. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 25,
      effect: { type: 'buffAlly', atkMultiplier: 1.4, duration: 25 },
    },
    {
      id: 'instructor_s3', name: 'Pride of Vanguard',
      description: 'Self ATK +80%, all melee allies gain ATK +50%. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 50, spInitial: 20,
      durationType: 'duration', duration: 20,
      effect: { type: 'statBuff', atkMultiplier: 1.8 },
    },
  ],
  soloblade: [
    {
      id: 'soloblade_s1', name: 'Bloodthirst',
      description: 'ATK +40%, heal on attack increased by 50%. Activates automatically when SP is full. Lasts 20s.',
      spRecovery: 'auto', activation: 'auto', spCost: 5, spInitial: 0,
      durationType: 'duration', duration: 20,
      effect: { type: 'statBuff', atkMultiplier: 1.4, healOnAttackMultiplier: 1.5 },
    },
    {
      id: 'soloblade_s2', name: 'Unyielding',
      description: 'ATK +80%, DEF +80%, heals on each attack. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 35, spInitial: 10,
      durationType: 'duration', duration: 25,
      effect: { type: 'statBuff', atkMultiplier: 1.8, defMultiplier: 1.8, hpRegenPerSecond: 0 },
    },
    {
      id: 'soloblade_s3', name: 'Xanxia Sword',
      description: 'ATK +120%, attacks ignore 100% DEF. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 50, spInitial: 20,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 2.2, defIgnore: 100 },
    },
  ],
  reaper: [
    {
      id: 'reaper_s1', name: 'Reaping',
      description: 'ATK +30%, heal per enemy hit doubled. Activates automatically. Lasts 20s.',
      spRecovery: 'auto', activation: 'auto', spCost: 5, spInitial: 0,
      durationType: 'duration', duration: 20,
      effect: { type: 'statBuff', atkMultiplier: 1.3, healOnAttackMultiplier: 2 },
    },
    {
      id: 'reaper_s2', name: 'Harvest',
      description: 'ATK +60%, attacks hit all enemies in wide melee range. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 35, spInitial: 10,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.6, targetCount: 99 },
    },
    {
      id: 'reaper_s3', name: 'Blood Scythe',
      description: 'ATK +100%, attacks hit all enemies in 2-tile radius. Lasts 12s.',
      spRecovery: 'auto', activation: 'manual', spCost: 50, spInitial: 20,
      durationType: 'duration', duration: 12,
      effect: { type: 'enhanceAttack', atkMultiplier: 2, targetCount: 99, splash: { radius: 2, damageMultiplier: 1 } },
    },
  ],
  crusher: [
    {
      id: 'crusher_s1', name: 'Crush',
      description: 'Next attack deals 200% ATK as true damage.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2, trueDamage: true },
    },
    {
      id: 'crusher_s2', name: 'Shatter',
      description: 'ATK +40%, attacks deal true splash damage in 1-tile radius. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 10,
      durationType: 'duration', duration: 20,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.4, trueDamage: true, splash: { radius: 1, damageMultiplier: 1 } },
    },
    {
      id: 'crusher_s3', name: 'Annihilate',
      description: 'ATK +120%, attacks hit all enemies in melee range as true damage. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 55, spInitial: 25,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 2.2, trueDamage: true, targetCount: 99 },
    },
  ],
  earthshaker: [
    {
      id: 'earthshaker_s1', name: 'Shockwave',
      description: 'Next attack deals 200% ATK in a 3-tile line.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2, targetCount: 99 },
    },
    {
      id: 'earthshaker_s2', name: 'Tremor',
      description: 'ATK +30%, attacks trigger 1-tile splash around target. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 35, spInitial: 10,
      durationType: 'duration', duration: 20,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.3, splash: { radius: 1, damageMultiplier: 1 } },
    },
    {
      id: 'earthshaker_s3', name: 'Lotus Hammer',
      description: 'ATK +80%, attacks hit all enemies in 2-tile radius. Lasts 12s.',
      spRecovery: 'auto', activation: 'manual', spCost: 50, spInitial: 20,
      durationType: 'duration', duration: 12,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.8, targetCount: 99, splash: { radius: 2, damageMultiplier: 1 } },
    },
  ],
  protector: [
    {
      id: 'protector_s1', name: 'DEF Up',
      description: 'DEF +80%. Lasts 30s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 30,
      effect: { type: 'statBuff', defMultiplier: 1.8 },
    },
    {
      id: 'protector_s2', name: 'Shell Defense',
      description: 'DEF +200%, Block +1, restores 6% HP per second. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 50, spInitial: 20,
      durationType: 'duration', duration: 20,
      effect: { type: 'statBuff', defMultiplier: 3, blockBonus: 1, hpRegenPerSecond: { percent: 6 } },
    },
    {
      id: 'protector_s3', name: 'Self-Sustain',
      description: 'When HP falls below 40%, automatically gain DEF +100% and ATK +50%. Lasts 15s.',
      spRecovery: 'auto', activation: 'auto', spCost: 40, spInitial: 0,
      durationType: 'duration', duration: 15,
      effect: { type: 'special', description: 'conditional_statbuff' },
    },
  ],
  guardian: [
    {
      id: 'guardian_s1', name: 'Healing Wave',
      description: 'Next heal amount tripled (300% ATK).',
      spRecovery: 'auto', activation: 'auto', spCost: 5, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'heal', amountMultiplier: 3, range: 'ally' },
    },
    {
      id: 'guardian_s2', name: 'Medical Mode',
      description: 'Heal interval halved, heals up to 2 allies per tick. Lasts 30s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 30,
      effect: { type: 'statBuff', aspdBonus: 100 },
    },
    {
      id: 'guardian_s3', name: 'Calcification',
      description: 'DEF +80%, heals all allies in range every 2s, enemies in range take 40% more damage. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 60, spInitial: 25,
      durationType: 'duration', duration: 20,
      effect: { type: 'statBuff', defMultiplier: 1.8 },
    },
  ],
  fortress_defender: [
    {
      id: 'fortress_s1', name: 'Shelling',
      description: 'Next ranged attack deals 180% splash damage in 1-tile radius.',
      spRecovery: 'offensive', activation: 'auto', spCost: 5, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 1.8, splash: { radius: 1, damageMultiplier: 1 } },
    },
    {
      id: 'fortress_s2', name: 'Bombardment',
      description: 'Ranged attacks hit all enemies in 2-tile radius. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 25,
      effect: { type: 'enhanceAttack', targetCount: 99, splash: { radius: 2, damageMultiplier: 1 } },
    },
    {
      id: 'fortress_s3', name: 'Artillery',
      description: 'ATK +80%, attacks hit all enemies in range. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 55, spInitial: 25,
      durationType: 'duration', duration: 20,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.8, targetCount: 99 },
    },
  ],
  juggernaut: [
    {
      id: 'juggernaut_s1', name: 'Indomitable',
      description: 'When HP falls below 30%, gain a shield equal to 30% of max HP.',
      spRecovery: 'auto', activation: 'auto', spCost: 10, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'survival', shieldPercent: 30 },
    },
    {
      id: 'juggernaut_s2', name: 'Juggernaut Mode',
      description: 'Block +2, restores 5% HP per second, attacks deal splash damage. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 10,
      durationType: 'duration', duration: 20,
      effect: { type: 'statBuff', blockBonus: 2, hpRegenPerSecond: { percent: 5 } },
    },
    {
      id: 'juggernaut_s3', name: 'Unstoppable',
      description: 'ATK +150%, DEF +100%, attacks hit all blocked enemies. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 55, spInitial: 20,
      durationType: 'duration', duration: 15,
      effect: { type: 'statBuff', atkMultiplier: 2.5, defMultiplier: 2 },
    },
  ],
  core_caster: [
    {
      id: 'core_caster_s1', name: 'Tactical Chant',
      description: 'ASPD +60. Lasts 30s.',
      spRecovery: 'auto', activation: 'manual', spCost: 30, spInitial: 0,
      durationType: 'duration', duration: 30,
      effect: { type: 'statBuff', aspdBonus: 60 },
    },
    {
      id: 'core_caster_s2', name: 'Spirit Burst',
      description: 'Fires homing projectiles at random enemies, each dealing 45% ATK. Activates automatically. Lasts 25s.',
      spRecovery: 'auto', activation: 'auto', spCost: 100, spInitial: 50,
      durationType: 'duration', duration: 25,
      effect: { type: 'special', description: 'homing_projectiles' },
    },
    {
      id: 'core_caster_s3', name: 'Volcano',
      description: 'ATK +130%, attacks deal splash damage in 1-tile radius, range extended by +1 tile. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 80, spInitial: 40,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 2.3, splash: { radius: 1, damageMultiplier: 1 } },
    },
  ],
  blast_caster: [
    {
      id: 'blast_caster_s1', name: 'Ignition',
      description: 'Next attack deals 200% ATK in a line.',
      spRecovery: 'auto', activation: 'auto', spCost: 5, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2 },
    },
    {
      id: 'blast_caster_s2', name: 'Scorched Earth',
      description: 'Attack pattern becomes a 3-tile-wide line. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 25,
      effect: { type: 'enhanceAttack', targetCount: 99 },
    },
    {
      id: 'blast_caster_s3', name: 'Pyroclasm',
      description: 'ATK +100%, leaves burning ground dealing 30% ATK per second for 5s. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 60, spInitial: 25,
      durationType: 'duration', duration: 20,
      effect: { type: 'enhanceAttack', atkMultiplier: 2 },
    },
  ],
  splash_caster: [
    {
      id: 'splash_caster_s1', name: 'Burst',
      description: 'Next attack deals 200% ATK splash damage.',
      spRecovery: 'auto', activation: 'auto', spCost: 5, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2, splash: { radius: 1, damageMultiplier: 1 } },
    },
    {
      id: 'splash_caster_s2', name: 'Firestorm',
      description: 'Splash radius increased by +1 tile, ATK +30%. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 25,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.3, splash: { radius: 2, damageMultiplier: 1 } },
    },
    {
      id: 'splash_caster_s3', name: 'Cataclysm',
      description: 'ATK +80%, attacks hit all enemies in splash range. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 55, spInitial: 25,
      durationType: 'duration', duration: 20,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.8, targetCount: 99 },
    },
  ],
  chain_caster: [
    {
      id: 'chain_caster_s1', name: 'Static',
      description: 'Next attack chains to 3 targets at 85% damage per jump.',
      spRecovery: 'auto', activation: 'auto', spCost: 5, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack' },
    },
    {
      id: 'chain_caster_s2', name: 'Overload',
      description: 'Chains to 4 targets with no damage falloff. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 25,
      effect: { type: 'enhanceAttack' },
    },
    {
      id: 'chain_caster_s3', name: 'Lightning Storm',
      description: 'ATK +100%, chains to all enemies in range. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 60, spInitial: 25,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 2 },
    },
  ],
  sniper: [
    {
      id: 'sniper_s1', name: 'Charging Mode',
      description: 'Next attack fires 3 shots at 120% ATK each.',
      spRecovery: 'offensive', activation: 'auto', spCost: 5, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 1.2, hitCount: 3 },
    },
    {
      id: 'sniper_s2', name: 'Shooting Mode',
      description: 'Fires 4 shots per attack at 110% ATK each. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 35, spInitial: 15,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.1, hitCount: 4 },
    },
    {
      id: 'sniper_s3', name: 'Overloading Mode',
      description: 'Fires 5 shots per attack with slight ASPD bonus. Activates automatically. Lasts 15s.',
      spRecovery: 'auto', activation: 'auto', spCost: 30, spInitial: 20,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.1, hitCount: 5, aspdBonus: 20 },
    },
  ],
  deadeye: [
    {
      id: 'deadeye_s1', name: 'Precision',
      description: 'Next attack deals 250% ATK.',
      spRecovery: 'auto', activation: 'auto', spCost: 5, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2.5 },
    },
    {
      id: 'deadeye_s2', name: 'Snipe',
      description: 'Deals 400% ATK to target enemy.',
      spRecovery: 'auto', activation: 'manual', spCost: 25, spInitial: 10,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 4 },
    },
    {
      id: 'deadeye_s3', name: 'Full-Auto',
      description: 'Range extends to full map, ATK +60%. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 45, spInitial: 20,
      durationType: 'duration', duration: 25,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.6 },
    },
  ],
  heavyshooter: [
    {
      id: 'heavyshooter_s1', name: 'Point Blank',
      description: 'Next attack deals 200% ATK.',
      spRecovery: 'offensive', activation: 'auto', spCost: 4, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2 },
    },
    {
      id: 'heavyshooter_s2', name: 'Suppressing Fire',
      description: 'ATK +50%, attacks slow enemies by 40% for 2s. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 35, spInitial: 10,
      durationType: 'duration', duration: 20,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.5, slowFactor: 0.4 },
    },
    {
      id: 'heavyshooter_s3', name: 'Devastator',
      description: 'ATK +80%, attacks hit all enemies in range. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 45, spInitial: 15,
      durationType: 'duration', duration: 15,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.8, targetCount: 99 },
    },
  ],
  artilleryman: [
    {
      id: 'artilleryman_s1', name: 'High Explosive',
      description: 'Next attack deals 220% splash damage in 1-tile radius.',
      spRecovery: 'offensive', activation: 'auto', spCost: 5, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', atkMultiplier: 2.2, splash: { radius: 1, damageMultiplier: 1 } },
    },
    {
      id: 'artilleryman_s2', name: 'Barrage',
      description: 'ASPD +40, attacks hit all enemies in 2-tile radius. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 25,
      effect: { type: 'enhanceAttack', aspdBonus: 40, splash: { radius: 2, damageMultiplier: 1 }, targetCount: 99 },
    },
    {
      id: 'artilleryman_s3', name: 'Orbital Strike',
      description: 'ATK +60%, attacks slow enemies by 30% for 2s. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 50, spInitial: 20,
      durationType: 'duration', duration: 20,
      effect: { type: 'enhanceAttack', atkMultiplier: 1.6, slowFactor: 0.3 },
    },
  ],
  decel_binder: [
    {
      id: 'decel_binder_s1', name: 'Web',
      description: 'Next attack binds enemy for 2.5s (cannot move or attack).',
      spRecovery: 'offensive', activation: 'auto', spCost: 5, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'enhanceAttack', binds: true, slowFactor: 1 },
    },
    {
      id: 'decel_binder_s2', name: 'Glacial Field',
      description: 'All enemies in attack range slowed by 60%. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 25,
      effect: { type: 'debuffEnemies', slowFactor: 0.6, duration: 25 },
    },
    {
      id: 'decel_binder_s3', name: 'Time Warp',
      description: 'Range +1, ATK +50%, enemies in range slowed by 80%. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 60, spInitial: 25,
      durationType: 'duration', duration: 20,
      effect: { type: 'debuffEnemies', slowFactor: 0.8, duration: 20 },
    },
  ],
  bard_supporter: [
    {
      id: 'bard_s1', name: 'Inspire',
      description: 'All allies in range gain ATK +20%. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 30, spInitial: 10,
      durationType: 'duration', duration: 25,
      effect: { type: 'buffAlly', atkMultiplier: 1.2, duration: 25 },
    },
    {
      id: 'bard_s2', name: 'Ballad',
      description: 'All allies in range gain ATK +40% and DEF +30%. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 20,
      effect: { type: 'buffAlly', atkMultiplier: 1.4, defMultiplier: 1.3, duration: 20 },
    },
    {
      id: 'bard_s3', name: 'Requiem',
      description: 'All allies in range gain ATK +80% and restore 5% HP per second. Lasts 15s.',
      spRecovery: 'auto', activation: 'manual', spCost: 60, spInitial: 25,
      durationType: 'duration', duration: 15,
      effect: { type: 'buffAlly', atkMultiplier: 1.8, hpRegen: 5, duration: 15 },
    },
  ],
  medic_st: [
    {
      id: 'medic_st_s1', name: 'Emergency Triage',
      description: 'Next heal amount doubled (200% ATK).',
      spRecovery: 'auto', activation: 'auto', spCost: 5, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'heal', amountMultiplier: 2, range: 'ally' },
    },
    {
      id: 'medic_st_s2', name: 'Medic Overdrive',
      description: 'ASPD +60, heals up to 2 targets per tick. Lasts 25s.',
      spRecovery: 'auto', activation: 'manual', spCost: 35, spInitial: 10,
      durationType: 'duration', duration: 25,
      effect: { type: 'statBuff', aspdBonus: 60 },
    },
    {
      id: 'medic_st_s3', name: 'Battlefield Revival',
      description: 'Heals all allies in range for 250% ATK.',
      spRecovery: 'auto', activation: 'manual', spCost: 50, spInitial: 20,
      durationType: 'instant',
      effect: { type: 'heal', amountMultiplier: 2.5, range: 'allies' },
    },
  ],
  incantation_medic: [
    {
      id: 'incantation_medic_s1', name: 'Leech Shot',
      description: 'Next attack heals the lowest HP ally for 50% of damage dealt.',
      spRecovery: 'offensive', activation: 'auto', spCost: 5, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'heal', amountMultiplier: 0.5, range: 'ally' },
    },
    {
      id: 'incantation_medic_s2', name: 'Purifying Flames',
      description: 'Attacks heal all allies in range for 30% of damage dealt. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 20,
      effect: { type: 'heal', amountMultiplier: 0.3, range: 'allies' },
    },
    {
      id: 'incantation_medic_s3', name: 'Holy Nova',
      description: 'Deals 300% ATK to all enemies and heals all allies for 200% ATK.',
      spRecovery: 'auto', activation: 'manual', spCost: 55, spInitial: 25,
      durationType: 'instant',
      effect: { type: 'special', description: 'aoe_damage_and_heal' },
    },
  ],
  medic_multi: [
    {
      id: 'medic_multi_s1', name: 'Team Heal',
      description: 'Next heal also heals 2 nearby allies for 50% of the amount.',
      spRecovery: 'auto', activation: 'auto', spCost: 5, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'heal', amountMultiplier: 1, targetCount: 3, range: 'allies' },
    },
    {
      id: 'medic_multi_s2', name: 'Mass Recovery',
      description: 'Heals 3 additional targets per tick, all healing increased by 30%. Lasts 30s.',
      spRecovery: 'auto', activation: 'manual', spCost: 40, spInitial: 15,
      durationType: 'duration', duration: 30,
      effect: { type: 'statBuff', healOnAttackMultiplier: 1.3 },
    },
    {
      id: 'medic_multi_s3', name: 'Rejuvenation',
      description: 'Range +1, all allies in range heal for 100% ATK every 2s. Lasts 20s.',
      spRecovery: 'auto', activation: 'manual', spCost: 60, spInitial: 25,
      durationType: 'duration', duration: 20,
      effect: { type: 'heal', amountMultiplier: 1, range: 'allies' },
    },
  ],
  roadblock: [],
  pusher: [
    {
      id: 'pusher_s1', name: 'Shockwave',
      description: 'Pushes all enemies in range away from the unit by 2 tiles.',
      spRecovery: 'auto', activation: 'manual', spCost: 12, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'displace', direction: 'away', tiles: 2, radius: 2 },
    },
  ],
  puller: [
    {
      id: 'puller_s1', name: 'Hook',
      description: 'Pulls all enemies in range toward the unit by 1 tile.',
      spRecovery: 'auto', activation: 'manual', spCost: 10, spInitial: 0,
      durationType: 'instant',
      effect: { type: 'displace', direction: 'toward', tiles: 1, radius: 3 },
    },
  ],
}
