import { UnitConfig } from '../types/index'
import { RANGE_PATTERNS } from '../shared/utils/GridMath'

export const UNIT_CONFIGS: UnitConfig[] = [
  {
    id: 'vanguard',
    name: 'Vanguard',
    type: 'ground',
    hp: 800,
    atk: 150,
    def: 100,
    damageType: 'kinetic',
    attackInterval: 1.2,
    rangePattern: RANGE_PATTERNS.melee,
    blockCount: 1,
    dpCost: 6,
    redeployTime: 10,
    color: 0x3498db,
  },
  {
    id: 'guard',
    name: 'Guard',
    type: 'ground',
    hp: 1200,
    atk: 300,
    def: 150,
    damageType: 'kinetic',
    attackInterval: 1.5,
    rangePattern: RANGE_PATTERNS.melee,
    blockCount: 1,
    dpCost: 12,
    redeployTime: 15,
    color: 0xe74c3c,
  },
  {
    id: 'defender',
    name: 'Defender',
    type: 'ground',
    hp: 2500,
    atk: 200,
    def: 350,
    damageType: 'kinetic',
    attackInterval: 1.8,
    rangePattern: RANGE_PATTERNS.melee,
    blockCount: 3,
    dpCost: 15,
    redeployTime: 20,
    color: 0x2ecc71,
  },
  {
    id: 'sniper',
    name: 'Sniper',
    type: 'ranged',
    hp: 600,
    atk: 350,
    def: 50,
    damageType: 'kinetic',
    attackInterval: 1.8,
    rangePattern: RANGE_PATTERNS.cross2,
    blockCount: 0,
    dpCost: 14,
    redeployTime: 15,
    color: 0xf39c12,
  },
  {
    id: 'caster',
    name: 'Caster',
    type: 'ranged',
    hp: 700,
    atk: 450,
    def: 80,
    damageType: 'thermal',
    attackInterval: 2.2,
    rangePattern: RANGE_PATTERNS.diamond2,
    blockCount: 0,
    dpCost: 18,
    redeployTime: 20,
    color: 0x9b59b6,
  },
  {
    id: 'medic',
    name: 'Medic',
    type: 'ranged',
    hp: 500,
    atk: 0,
    def: 40,
    damageType: 'thermal',
    attackInterval: 2.0,
    rangePattern: RANGE_PATTERNS.cross2,
    blockCount: 0,
    dpCost: 12,
    redeployTime: 15,
    color: 0x1abc9c,
  },
]
