import { UnitConfig, UnitTrait } from '../types/index'
import { RANGE_PATTERNS } from '../shared/utils/GridMath'

export const UNIT_CONFIGS: UnitConfig[] = [
  {
    id: 'pioneer',
    name: 'Vanguard',
    archetype: 'vanguard',
    subtypeLabel: 'Pioneer',
    type: 'ground',
    hp: 1200,
    atk: 300,
    def: 230,
    insulation: 0,
    damageType: 'kinetic',
    attackInterval: 1.05,
    rangePattern: RANGE_PATTERNS.meleeFront,
    blockCount: 2,
    dpCost: 12,
    redeployTime: 10,
    color: 0x3498db,
    traits: [{ traitId: UnitTrait.BlocksTwo }],
  },
  {
    id: 'fighter',
    name: 'Guard',
    archetype: 'guard',
    subtypeLabel: 'Fighter',
    type: 'ground',
    hp: 1800,
    atk: 360,
    def: 220,
    insulation: 0,
    damageType: 'kinetic',
    attackInterval: 0.78,
    rangePattern: RANGE_PATTERNS.meleeFront,
    blockCount: 1,
    dpCost: 9,
    redeployTime: 15,
    color: 0xe74c3c,
    traits: [{ traitId: UnitTrait.FastAttack }],
  },
  {
    id: 'arts_fighter',
    name: 'Guard',
    archetype: 'guard',
    subtypeLabel: 'Arts Fighter',
    type: 'ground',
    hp: 1400,
    atk: 280,
    def: 180,
    insulation: 15,
    damageType: 'thermal',
    attackInterval: 1.25,
    rangePattern: RANGE_PATTERNS.meleeFront,
    blockCount: 1,
    dpCost: 12,
    redeployTime: 15,
    color: 0x9b59b6,
    traits: [{ traitId: UnitTrait.ArtsDamage }],
  },
  {
    id: 'protector',
    name: 'Defender',
    archetype: 'defender',
    subtypeLabel: 'Protector',
    type: 'ground',
    hp: 2200,
    atk: 280,
    def: 380,
    insulation: 0,
    damageType: 'kinetic',
    attackInterval: 1.2,
    rangePattern: RANGE_PATTERNS.selfOnly,
    blockCount: 3,
    dpCost: 19,
    redeployTime: 20,
    color: 0x2ecc71,
    traits: [{ traitId: UnitTrait.BlocksThree }],
  },
  {
    id: 'core_caster',
    name: 'Caster',
    archetype: 'caster',
    subtypeLabel: 'Core Caster',
    type: 'ranged',
    hp: 1050,
    atk: 410,
    def: 80,
    insulation: 15,
    damageType: 'thermal',
    attackInterval: 1.6,
    rangePattern: RANGE_PATTERNS.ranged4x3,
    blockCount: 0,
    dpCost: 19,
    redeployTime: 20,
    color: 0x9b59b6,
    traits: [{ traitId: UnitTrait.ArtsDamage }],
  },
  {
    id: 'sniper',
    name: 'Sniper',
    archetype: 'sniper',
    subtypeLabel: 'Marksman',
    type: 'ranged',
    hp: 1000,
    atk: 310,
    def: 100,
    insulation: 0,
    damageType: 'kinetic',
    attackInterval: 1.0,
    rangePattern: RANGE_PATTERNS.ranged4x3,
    blockCount: 0,
    dpCost: 12,
    redeployTime: 15,
    color: 0xf39c12,
    traits: [],
  },
  {
    id: 'swordmaster',
    name: 'Guard',
    archetype: 'guard',
    subtypeLabel: 'Swordmaster',
    type: 'ground',
    hp: 1800,
    atk: 400,
    def: 200,
    insulation: 0,
    damageType: 'kinetic',
    attackInterval: 1.05,
    rangePattern: RANGE_PATTERNS.meleeFront,
    blockCount: 1,
    dpCost: 15,
    redeployTime: 15,
    color: 0xc0392b,
    traits: [{ traitId: UnitTrait.DoubleHit }],
  },
  {
    id: 'deadeye',
    name: 'Sniper',
    archetype: 'sniper',
    subtypeLabel: 'Deadeye',
    type: 'ranged',
    hp: 800,
    atk: 450,
    def: 70,
    insulation: 0,
    damageType: 'kinetic',
    attackInterval: 1.6,
    rangePattern: RANGE_PATTERNS.ranged4x3,
    blockCount: 0,
    dpCost: 15,
    redeployTime: 15,
    color: 0xe67e22,
    traits: [{ traitId: UnitTrait.TargetingLowestDef }],
  },
  {
    id: 'charger',
    name: 'Vanguard',
    archetype: 'vanguard',
    subtypeLabel: 'Charger',
    type: 'ground',
    hp: 1100,
    atk: 290,
    def: 200,
    insulation: 0,
    damageType: 'kinetic',
    attackInterval: 1.05,
    rangePattern: RANGE_PATTERNS.meleeFront,
    blockCount: 1,
    dpCost: 10,
    redeployTime: 10,
    color: 0x2980b9,
    traits: [
      { traitId: UnitTrait.DPOnKill, value: 1 },
      { traitId: UnitTrait.FullRefundRetreat },
    ],
  },
  {
    id: 'heavyshooter',
    name: 'Sniper',
    archetype: 'sniper',
    subtypeLabel: 'Heavyshooter',
    type: 'ranged',
    hp: 1100,
    atk: 480,
    def: 120,
    insulation: 0,
    damageType: 'kinetic',
    attackInterval: 1.5,
    rangePattern: RANGE_PATTERNS.pointBlank,
    blockCount: 0,
    dpCost: 14,
    redeployTime: 15,
    color: 0xf1c40f,
    traits: [],
  },
  {
    id: 'blast_caster',
    name: 'Caster',
    archetype: 'caster',
    subtypeLabel: 'Blast Caster',
    type: 'ranged',
    hp: 900,
    atk: 350,
    def: 60,
    insulation: 15,
    damageType: 'thermal',
    attackInterval: 2.3,
    rangePattern: RANGE_PATTERNS.line4,
    blockCount: 0,
    dpCost: 23,
    redeployTime: 20,
    color: 0x8e44ad,
    traits: [
      { traitId: UnitTrait.LinearAoE },
      { traitId: UnitTrait.ArtsDamage },
    ],
  },
  {
    id: 'earthshaker',
    name: 'Guard',
    archetype: 'guard',
    subtypeLabel: 'Earthshaker',
    type: 'ground',
    hp: 1600,
    atk: 350,
    def: 200,
    insulation: 0,
    damageType: 'kinetic',
    attackInterval: 1.05,
    rangePattern: RANGE_PATTERNS.meleeFront,
    blockCount: 2,
    dpCost: 18,
    redeployTime: 15,
    color: 0xd35400,
    traits: [{ traitId: UnitTrait.LinearAoE }],
  },
  {
    id: 'artilleryman',
    name: 'Sniper',
    archetype: 'sniper',
    subtypeLabel: 'Artilleryman',
    type: 'ranged',
    hp: 900,
    atk: 380,
    def: 80,
    insulation: 0,
    damageType: 'kinetic',
    attackInterval: 2.0,
    rangePattern: RANGE_PATTERNS.ranged5x3,
    blockCount: 0,
    dpCost: 21,
    redeployTime: 20,
    color: 0xe67e22,
    splashConfig: { radius: 1, damageMultiplier: 0.5 },
    traits: [{ traitId: UnitTrait.AoESplash }],
  },
  {
    id: 'splash_caster',
    name: 'Caster',
    archetype: 'caster',
    subtypeLabel: 'Splash Caster',
    type: 'ranged',
    hp: 950,
    atk: 380,
    def: 60,
    insulation: 20,
    damageType: 'thermal',
    attackInterval: 2.0,
    rangePattern: RANGE_PATTERNS.ranged4x3,
    blockCount: 0,
    dpCost: 22,
    redeployTime: 20,
    color: 0x8e44ad,
    splashConfig: { radius: 1, damageMultiplier: 0.5 },
    traits: [
      { traitId: UnitTrait.AoESplash },
      { traitId: UnitTrait.ArtsDamage },
    ],
  },
  {
    id: 'chain_caster',
    name: 'Caster',
    archetype: 'caster',
    subtypeLabel: 'Chain Caster',
    type: 'ranged',
    hp: 900,
    atk: 340,
    def: 50,
    insulation: 15,
    damageType: 'thermal',
    attackInterval: 2.0,
    rangePattern: RANGE_PATTERNS.ranged4x3,
    blockCount: 0,
    dpCost: 19,
    redeployTime: 20,
    color: 0x9b59b6,
    traits: [
      { traitId: UnitTrait.ChainJump, radius: 2, maxTargets: 3, damageFalloff: 0.5 },
      { traitId: UnitTrait.ArtsDamage },
    ],
  },
  {
    id: 'decel_binder',
    name: 'Supporter',
    archetype: 'supporter',
    subtypeLabel: 'Decel Binder',
    type: 'ranged',
    hp: 850,
    atk: 200,
    def: 70,
    insulation: 0,
    damageType: 'kinetic',
    attackInterval: 1.9,
    rangePattern: RANGE_PATTERNS.ranged4x3,
    blockCount: 0,
    dpCost: 14,
    redeployTime: 15,
    color: 0x1abc9c,
    traits: [{ traitId: UnitTrait.SlowOnHit, value: 0.5, duration: 2 }],
  },
]
