import { UnitConfig, UnitTrait } from '../types/index'
import { RANGE_PATTERNS } from '../shared/utils/GridMath'
import { SKILLS } from './skills'

export const UNIT_CONFIGS: UnitConfig[] = [
  {
    id: 'pioneer',
    name: 'Vanguard',
    archetype: 'vanguard',
    subtypeLabel: 'Pioneer',
    type: 'ground',
    hp: 1200,
    atk: 300,
    def: 230,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 1.05,
    rangePattern: RANGE_PATTERNS.meleeFront,
    blockCount: 2,
    dpCost: 12,
    redeployTime: 10,
    color: 0x3498db,
    traits: [{ traitId: UnitTrait.BlocksTwo }],
    skills: SKILLS['pioneer'],
  },
  {
    id: 'fighter',
    name: 'Guard',
    archetype: 'guard',
    subtypeLabel: 'Fighter',
    type: 'ground',
    hp: 1800,
    atk: 360,
    def: 220,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 0.78,
    rangePattern: RANGE_PATTERNS.meleeFront,
    blockCount: 1,
    dpCost: 9,
    redeployTime: 15,
    color: 0xe74c3c,
    traits: [{ traitId: UnitTrait.FastAttack }],
    skills: SKILLS['fighter'],
  },
  {
    id: 'arts_fighter',
    name: 'Guard',
    archetype: 'guard',
    subtypeLabel: 'Arts Fighter',
    type: 'ground',
    hp: 1400,
    atk: 280,
    def: 180,
    res: 15,
    damageType: 'thermal',
    attackInterval: 1.25,
    rangePattern: RANGE_PATTERNS.meleeFront,
    blockCount: 1,
    dpCost: 12,
    redeployTime: 15,
    color: 0x9b59b6,
    traits: [{ traitId: UnitTrait.ArtsDamage }],
    skills: SKILLS['arts_fighter'],
  },
  {
    id: 'centurion_guard',
    name: 'Guard',
    archetype: 'guard',
    subtypeLabel: 'Centurion',
    type: 'ground',
    hp: 1800,
    atk: 320,
    def: 220,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 1.2,
    rangePattern: RANGE_PATTERNS.meleeFront,
    blockCount: 2,
    dpCost: 14,
    redeployTime: 15,
    color: 0xe74c3c,
    traits: [{ traitId: UnitTrait.AoEMeleeBlockCapped }, { traitId: UnitTrait.BlocksTwo }],
    skills: SKILLS['centurion_guard'],
  },
  {
    id: 'protector',
    name: 'Defender',
    archetype: 'defender',
    subtypeLabel: 'Protector',
    type: 'ground',
    hp: 2200,
    atk: 280,
    def: 380,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 1.5,
    rangePattern: RANGE_PATTERNS.selfOnly,
    blockCount: 3,
    dpCost: 19,
    redeployTime: 20,
    color: 0x2ecc71,
    traits: [{ traitId: UnitTrait.BlocksThree }],
    skills: SKILLS['protector'],
  },
  {
    id: 'arts_protector',
    name: 'Defender',
    archetype: 'defender',
    subtypeLabel: 'Arts Protector',
    type: 'ground',
    hp: 2200,
    atk: 320,
    def: 350,
    res: 20,
    damageType: 'thermal',
    attackInterval: 1.6,
    rangePattern: RANGE_PATTERNS.meleeFront,
    blockCount: 3,
    dpCost: 22,
    redeployTime: 20,
    color: 0x9b59b6,
    traits: [
      { traitId: UnitTrait.BlocksThree },
      { traitId: UnitTrait.ArtsDamage },
    ],
    skills: SKILLS['arts_protector'],
  },
  {
    id: 'sentry_protector',
    name: 'Defender',
    archetype: 'defender',
    subtypeLabel: 'Sentry Protector',
    type: 'ground',
    hp: 2200,
    atk: 300,
    def: 400,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 1.2,
    rangePattern: RANGE_PATTERNS.sentryRanged,
    blockCount: 3,
    dpCost: 19,
    redeployTime: 20,
    color: 0xf39c12,
    traits: [{ traitId: UnitTrait.BlocksThree }],
    skills: SKILLS['sentry_protector'],
  },
  {
    id: 'core_caster',
    name: 'Caster',
    archetype: 'caster',
    subtypeLabel: 'Core Caster',
    type: 'ranged',
    hp: 1050,
    atk: 410,
    def: 80,
    res: 15,
    damageType: 'thermal',
    attackInterval: 1.6,
    rangePattern: RANGE_PATTERNS.coreCaster,
    blockCount: 1,
    dpCost: 19,
    redeployTime: 20,
    color: 0x9b59b6,
    traits: [{ traitId: UnitTrait.ArtsDamage }],
    skills: SKILLS['core_caster'],
  },
  {
    id: 'sniper',
    name: 'Sniper',
    archetype: 'sniper',
    subtypeLabel: 'Marksman',
    type: 'ranged',
    hp: 1000,
    atk: 310,
    def: 100,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 1.0,
    rangePattern: RANGE_PATTERNS.ranged4x3,
    blockCount: 0,
    dpCost: 12,
    redeployTime: 15,
    color: 0xf39c12,
    traits: [{ traitId: UnitTrait.TargetingAerial }],
    skills: SKILLS['sniper'],
  },
  {
    id: 'swordmaster',
    name: 'Guard',
    archetype: 'guard',
    subtypeLabel: 'Swordmaster',
    type: 'ground',
    hp: 1800,
    atk: 400,
    def: 200,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 1.3,
    rangePattern: RANGE_PATTERNS.meleeFront,
    blockCount: 2,
    dpCost: 15,
    redeployTime: 15,
    color: 0xc0392b,
    traits: [{ traitId: UnitTrait.DoubleHit }],
    skills: SKILLS['swordmaster'],
  },
  {
    id: 'deadeye',
    name: 'Sniper',
    archetype: 'sniper',
    subtypeLabel: 'Deadeye',
    type: 'ranged',
    hp: 800,
    atk: 450,
    def: 70,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 1.6,
    rangePattern: RANGE_PATTERNS.deadeyeCross,
    blockCount: 0,
    dpCost: 15,
    redeployTime: 15,
    color: 0xe67e22,
    traits: [{ traitId: UnitTrait.TargetingLowestDef }],
    skills: SKILLS['deadeye'],
  },
  {
    id: 'charger',
    name: 'Vanguard',
    archetype: 'vanguard',
    subtypeLabel: 'Charger',
    type: 'ground',
    hp: 1100,
    atk: 290,
    def: 200,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 1.05,
    rangePattern: RANGE_PATTERNS.meleeFront,
    blockCount: 1,
    dpCost: 10,
    redeployTime: 10,
    color: 0x2980b9,
    traits: [
      { traitId: UnitTrait.DPOnKill, value: 1 },
      { traitId: UnitTrait.FullRefundRetreat },
    ],
    skills: SKILLS['charger'],
  },
  {
    id: 'heavyshooter',
    name: 'Sniper',
    archetype: 'sniper',
    subtypeLabel: 'Heavyshooter',
    type: 'ranged',
    hp: 1100,
    atk: 480,
    def: 120,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 1.5,
    rangePattern: RANGE_PATTERNS.pointBlank,
    blockCount: 0,
    dpCost: 14,
    redeployTime: 15,
    color: 0xf1c40f,
    traits: [],
    skills: SKILLS['heavyshooter'],
  },
  {
    id: 'blast_caster',
    name: 'Caster',
    archetype: 'caster',
    subtypeLabel: 'Blast Caster',
    type: 'ranged',
    hp: 900,
    atk: 460,
    def: 60,
    res: 15,
    damageType: 'thermal',
    attackInterval: 2.9,
    rangePattern: RANGE_PATTERNS.line4,
    blockCount: 1,
    dpCost: 23,
    redeployTime: 20,
    color: 0x8e44ad,
    traits: [
      { traitId: UnitTrait.LinearAoE },
      { traitId: UnitTrait.ArtsDamage },
    ],
    skills: SKILLS['blast_caster'],
  },
  {
    id: 'earthshaker',
    name: 'Guard',
    archetype: 'guard',
    subtypeLabel: 'Earthshaker',
    type: 'ground',
    hp: 1600,
    atk: 460,
    def: 200,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 1.8,
    rangePattern: RANGE_PATTERNS.meleeFront,
    blockCount: 2,
    dpCost: 18,
    redeployTime: 15,
    color: 0xd35400,
    splashConfig: { radius: 1, damageMultiplier: 0.5 },
    traits: [{ traitId: UnitTrait.AoESplash }],
    skills: SKILLS['earthshaker'],
  },
  {
    id: 'artilleryman',
    name: 'Sniper',
    archetype: 'sniper',
    subtypeLabel: 'Artilleryman',
    type: 'ranged',
    hp: 900,
    atk: 440,
    def: 80,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 2.8,
    rangePattern: RANGE_PATTERNS.ranged5x3,
    blockCount: 0,
    dpCost: 21,
    redeployTime: 20,
    color: 0xe67e22,
    splashConfig: { radius: 1, damageMultiplier: 0.5 },
    traits: [{ traitId: UnitTrait.AoESplash }],
    skills: SKILLS['artilleryman'],
  },
  {
    id: 'splash_caster',
    name: 'Caster',
    archetype: 'caster',
    subtypeLabel: 'Splash Caster',
    type: 'ranged',
    hp: 950,
    atk: 440,
    def: 60,
    res: 20,
    damageType: 'thermal',
    attackInterval: 2.9,
    rangePattern: RANGE_PATTERNS.ranged4x3,
    blockCount: 1,
    dpCost: 22,
    redeployTime: 20,
    color: 0x8e44ad,
    splashConfig: { radius: 1, damageMultiplier: 1 },
    traits: [
      { traitId: UnitTrait.AoESplash },
      { traitId: UnitTrait.ArtsDamage },
    ],
    skills: SKILLS['splash_caster'],
  },
  {
    id: 'chain_caster',
    name: 'Caster',
    archetype: 'caster',
    subtypeLabel: 'Chain Caster',
    type: 'ranged',
    hp: 800,
    atk: 430,
    def: 50,
    res: 15,
    damageType: 'thermal',
    attackInterval: 2.3,
    rangePattern: RANGE_PATTERNS.coreCaster,
    blockCount: 1,
    dpCost: 22,
    redeployTime: 20,
    color: 0x9b59b6,
    traits: [
      { traitId: UnitTrait.ChainJump, radius: 2, maxTargets: 3, damageFalloff: 0.85 },
      { traitId: UnitTrait.ArtsDamage },
    ],
    skills: SKILLS['chain_caster'],
  },
  {
    id: 'mech_accord_caster',
    name: 'Caster',
    archetype: 'caster',
    subtypeLabel: 'Mech-Accord Caster',
    type: 'ranged',
    hp: 800,
    atk: 280,
    def: 50,
    res: 15,
    damageType: 'thermal',
    attackInterval: 1.3,
    rangePattern: RANGE_PATTERNS.coreCaster,
    blockCount: 1,
    dpCost: 19,
    redeployTime: 20,
    color: 0x2980b9,
    traits: [
      { traitId: UnitTrait.DroneRamp, rampBasePercent: 0.2, rampIncrement: 0.15, rampMaxPercent: 1.1 },
      { traitId: UnitTrait.ArtsDamage },
    ],
    skills: SKILLS['mech_accord_caster'],
  },
  {
    id: 'decel_binder',
    name: 'Supporter',
    archetype: 'supporter',
    subtypeLabel: 'Decel Binder',
    type: 'ranged',
    hp: 850,
    atk: 200,
    def: 70,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 1.9,
    rangePattern: RANGE_PATTERNS.ranged4x3,
    blockCount: 0,
    dpCost: 14,
    redeployTime: 15,
    color: 0x1abc9c,
    traits: [{ traitId: UnitTrait.SlowOnHit, value: 0.5, duration: 2 }],
    skills: SKILLS['decel_binder'],
  },
  {
    id: 'lord_guard',
    name: 'Guard',
    archetype: 'guard',
    subtypeLabel: 'Lord',
    type: 'ground',
    hp: 1600,
    atk: 350,
    def: 220,
    res: 15,
    damageType: 'kinetic',
    attackInterval: 1.3,
    rangePattern: RANGE_PATTERNS.meleeFront,
    altRangePattern: RANGE_PATTERNS.lordRanged,
    blockCount: 2,
    dpCost: 16,
    redeployTime: 15,
    color: 0xc0392b,
    traits: [
      { traitId: UnitTrait.RangedWhenNotBlocking },
      { traitId: UnitTrait.RangedAttack80 },
    ],
    skills: SKILLS['lord_guard'],
  },
  {
    id: 'fortress_defender',
    name: 'Defender',
    archetype: 'defender',
    subtypeLabel: 'Fortress',
    type: 'ground',
    hp: 2000,
    atk: 300,
    def: 320,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 2.8,
    rangePattern: RANGE_PATTERNS.meleeFront,
    altRangePattern: RANGE_PATTERNS.fortressRanged,
    blockCount: 3,
    dpCost: 22,
    redeployTime: 20,
    color: 0x7f8c8d,
    splashConfig: { radius: 1, damageMultiplier: 1 },
    traits: [
      { traitId: UnitTrait.RangedWhenNotBlocking },
      { traitId: UnitTrait.AoESplash },
    ],
    skills: SKILLS['fortress_defender'],
  },
  {
    id: 'instructor_guard',
    name: 'Guard',
    archetype: 'guard',
    subtypeLabel: 'Instructor',
    type: 'ground',
    hp: 1400,
    atk: 350,
    def: 200,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 1.05,
    rangePattern: [[-3, 0], [-2, 0], [-1, 0], [0, 0]],
    blockCount: 2,
    dpCost: 15,
    redeployTime: 15,
    color: 0xe74c3c,
    traits: [
      { traitId: UnitTrait.RangedWhenNotBlocking },
      { traitId: UnitTrait.RangedAttack120 },
    ],
    skills: SKILLS['instructor_guard'],
  },
  {
    id: 'medic_st',
    name: 'Medic',
    archetype: 'medic',
    subtypeLabel: 'Medic',
    type: 'ranged',
    hp: 900,
    atk: 280,
    def: 60,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 2.85,
    rangePattern: RANGE_PATTERNS.ranged4x3,
    blockCount: 0,
    dpCost: 17,
    redeployTime: 15,
    color: 0x2ecc71,
    traits: [{ traitId: UnitTrait.HealAlly }],
    skills: SKILLS['medic_st'],
  },
  {
    id: 'incantation_medic',
    name: 'Medic',
    archetype: 'medic',
    subtypeLabel: 'Incantation Medic',
    type: 'ranged',
    hp: 850,
    atk: 280,
    def: 50,
    res: 15,
    damageType: 'thermal',
    attackInterval: 1.6,
    rangePattern: RANGE_PATTERNS.ranged4x3,
    blockCount: 0,
    dpCost: 18,
    redeployTime: 15,
    color: 0x27ae60,
    traits: [
      { traitId: UnitTrait.AttackHealsAlly },
      { traitId: UnitTrait.ArtsDamage },
    ],
    skills: SKILLS['incantation_medic'],
  },
  {
    id: 'chain_medic',
    name: 'Medic',
    archetype: 'medic',
    subtypeLabel: 'Chain Medic',
    type: 'ranged',
    hp: 850,
    atk: 240,
    def: 50,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 2.85,
    rangePattern: RANGE_PATTERNS.ranged4x3,
    blockCount: 0,
    dpCost: 17,
    redeployTime: 15,
    color: 0x1abc9c,
    traits: [{ traitId: UnitTrait.ChainHeal, radius: 2, maxTargets: 3, healFalloff: 0.25 }],
    skills: SKILLS['chain_medic'],
  },
  {
    id: 'medic_multi',
    name: 'Medic',
    archetype: 'medic',
    subtypeLabel: 'Multi Medic',
    type: 'ranged',
    hp: 900,
    atk: 190,
    def: 60,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 2.85,
    rangePattern: [[-2,-1],[-2,0],[-2,1],[-1,-1],[-1,0],[-1,1],[0,-1],[0,0],[0,1],[1,-1],[1,0],[1,1]],
    blockCount: 0,
    dpCost: 17,
    redeployTime: 15,
    color: 0x2ecc71,
    traits: [{ traitId: UnitTrait.HealMulti, value: 3 }],
    skills: SKILLS['medic_multi'],
  },
  {
    id: 'bard_supporter',
    name: 'Supporter',
    archetype: 'supporter',
    subtypeLabel: 'Bard',
    type: 'ranged',
    hp: 800,
    atk: 60,
    def: 50,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 2.5,
    rangePattern: RANGE_PATTERNS.bard,
    blockCount: 0,
    dpCost: 10,
    redeployTime: 15,
    color: 0x1abc9c,
    traits: [{ traitId: UnitTrait.AoEHoT, radius: 2, value: 60 }],
    skills: SKILLS['bard_supporter'],
  },
  {
    id: 'soloblade',
    name: 'Guard',
    archetype: 'guard',
    subtypeLabel: 'Soloblade',
    type: 'ground',
    hp: 2200,
    atk: 380,
    def: 200,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 1.2,
    rangePattern: RANGE_PATTERNS.meleeFront,
    blockCount: 1,
    dpCost: 13,
    redeployTime: 15,
    color: 0xe74c3c,
    traits: [{ traitId: UnitTrait.HealOnAttack, value: 50 }],
    skills: SKILLS['soloblade'],
  },
  {
    id: 'reaper',
    name: 'Guard',
    archetype: 'guard',
    subtypeLabel: 'Reaper',
    type: 'ground',
    hp: 1600,
    atk: 350,
    def: 200,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 1.3,
    rangePattern: RANGE_PATTERNS.meleeWide3,
    blockCount: 2,
    dpCost: 14,
    redeployTime: 15,
    color: 0xd35400,
    traits: [{ traitId: UnitTrait.AoEMelee }, { traitId: UnitTrait.HealOnAttack, value: 50 }, { traitId: UnitTrait.CannotBeHealed }],
    skills: SKILLS['reaper'],
  },
  {
    id: 'juggernaut',
    name: 'Defender',
    archetype: 'defender',
    subtypeLabel: 'Juggernaut',
    type: 'ground',
    hp: 3000,
    atk: 350,
    def: 500,
    res: 15,
    damageType: 'kinetic',
    attackInterval: 1.6,
    rangePattern: RANGE_PATTERNS.meleeFront,
    blockCount: 3,
    dpCost: 27,
    redeployTime: 20,
    color: 0x8b4513,
    canBeHealed: false,
    traits: [{ traitId: UnitTrait.BlocksThree }],
    skills: SKILLS['juggernaut'],
  },
  {
    id: 'crusher',
    name: 'Guard',
    archetype: 'guard',
    subtypeLabel: 'Crusher',
    type: 'ground',
    hp: 2200,
    atk: 500,
    def: 0,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 2.5,
    rangePattern: RANGE_PATTERNS.meleeFront,
    blockCount: 2,
    dpCost: 20,
    redeployTime: 15,
    color: 0x8e44ad,
    traits: [{ traitId: UnitTrait.AoEMeleeBlockCapped }],
    skills: SKILLS['crusher'],
  },
  {
    id: 'guardian',
    name: 'Defender',
    archetype: 'defender',
    subtypeLabel: 'Guardian',
    type: 'ground',
    hp: 2000,
    atk: 250,
    def: 300,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 1.2,
    rangePattern: RANGE_PATTERNS.selfOnly,
    blockCount: 3,
    dpCost: 20,
    redeployTime: 20,
    color: 0x45b39d,
    traits: [
      { traitId: UnitTrait.HealAlly },
      { traitId: UnitTrait.BlocksThree },
    ],
    skills: SKILLS['guardian'],
  },
  {
    id: 'roadblock',
    name: 'Roadblock',
    archetype: 'special',
    subtypeLabel: 'Barrier',
    type: 'ground',
    hp: 500,
    atk: 0,
    def: 300,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 99,
    rangePattern: RANGE_PATTERNS.selfOnly,
    blockCount: 3,
    dpCost: 5,
    redeployTime: 10,
    color: 0x888888,
    traits: [{ traitId: UnitTrait.BlocksThree }],
    skills: SKILLS['roadblock'],
  },
  {
    id: 'pusher',
    name: 'Push Stroker',
    archetype: 'specialist',
    subtypeLabel: 'Pusher',
    type: 'ground',
    hp: 1600,
    atk: 350,
    def: 180,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 1.2,
    rangePattern: RANGE_PATTERNS.meleeFront,
    blockCount: 2,
    dpCost: 16,
    redeployTime: 70,
    color: 0x00bcd4,
    traits: [{ traitId: UnitTrait.DeployAnywhere }, { traitId: UnitTrait.AoEMelee }],
    skills: SKILLS['pusher'],
  },
  {
    id: 'puller',
    name: 'Hookmaster',
    archetype: 'specialist',
    subtypeLabel: 'Puller',
    type: 'ground',
    hp: 1400,
    atk: 320,
    def: 160,
    res: 0,
    damageType: 'kinetic',
    attackInterval: 1.8,
    rangePattern: RANGE_PATTERNS.meleeExtended,
    blockCount: 2,
    dpCost: 14,
    redeployTime: 70,
    color: 0x7c4dff,
    traits: [{ traitId: UnitTrait.DeployAnywhere }, { traitId: UnitTrait.TargetingLowestDef }],
    skills: SKILLS['puller'],
  },
]
